### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by PentagramTr** [bijij/ViewImage#100]
Hi.
Could you add these codes in the script?

https://github.com/devunt/make-gis-great-again/blob/d6c9c48b7fa1836473a248bcdbf8593ad2c61f86/gis-vib.user.js

 ` en: 'View Image',`
 ` ru: 'Показать в полном размере',`
 `  ja: '画像を表示',`
 ` he: 'הצג תמונה',`
  ` fr: 'Voir l\'image',`
  ` sl: 'Ogled slike',`
  ` ar: 'عرض الصورة',`
  ` de: 'Bild ansehen',`
  ` tr: 'Resmi Görüntüle',`
  ` pt: 'Ver imagem',`
  ` lt: 'Rodyti vaizdą',`
  ` pl: 'Pokaż Obraz',`
  ` se: 'Visa bild',`
  ` uk: 'Показати зображення'`

**Comment by danid12** [comment]
why is it needed? you can edit it as you want in the settings page.

**Comment by bijij** [comment]
I'd prefer to have translations for both "View Image" and "Search by image" in all langs before i impliment localisation into the userscript

but this is definitely on the todo list
