### ISSUE TITLE
Not install in Mozilla 47.0

### ISSUE THREAD

**Issue by z2p18** [bijij/ViewImage#106]
I look this [http://skrinshoter.ru/s/080318/yobPemqB?a](url)
Why? What I must do?

**Comment by krystian3w** [comment]
> Why?

> https://addons.mozilla.org/en-US/firefox/addon/view-image/versions/
 > ### Works with Firefox for Android 48.0 and later, Firefox 48.0 and later

Possibile Firefox 47 no support WebExtension API version used in ViewImage.

---

>What I must do?

- You can XUL version [1.2](https://github.com/bijij/ViewImage/releases/tag/1.2) if still works.

   if no signed change value `xpinstall.signatures.required` :arrow_right:  `false` in **`about:config`**

- You can use userscript with Greasemonkey (maybe not works in Tamermonkey / violentmonkey / scriptish).

- You can try create fork for Firefox 47 and use unsigned XPI (in Firefox 47 works `xpinstall.signatures.required` :arrow_right:  `false`)
   - try download lastest version  "**save as**" option from right context menu:

      > https://addons.mozilla.org/firefox/downloads/file/891968/view_image-1.9.2-an+fx.xpi?src=version-history

       and drag and drop file to Firefox window.

- You can try update Firefox to 48 version from installer file:
   > https://ftp.mozilla.org/pub/firefox/releases/48.0.2/
