### ISSUE TITLE
Userscript outdated? 

### ISSUE THREAD

**Issue by psonnosp** [bijij/ViewImage#110]
Would it be possible to update the userscript to a later version? 1.6.3 doesn't seem to work any longer :(

I'm running Pale Moon 27.8.1 so it can't run the addon and the XUL is also dead.

**Comment by LuisE2001** [comment]
Same here, in Chromium has the 1.9.1 and it works, in Firefox we have the 1.9.0.

**Comment by bijij** [comment]
Hey there, google made some changes and I hadn't found time to update the userscript.
I should have it updated some time in the next few hours.

**Comment by deuxsonic** [comment]
All of the methods, both extension and script, have stopped working on all browsers. Google must have broken it completely with a change.

**Comment by psonnosp** [comment]
I updated it now so I'm at 1.9 but it still doesn't work so guess they've changed something again :(

**Comment by bijij** [comment]
I'll be looking into it again today. to see if I can figure out what's missing

**Comment by psonnosp** [comment]
Since it still doesn't work I guess this part of the project is on ice?
