### ISSUE TITLE
Layout a bit glitched since google changes and v1.9.2. 

### ISSUE THREAD

**Issue by mzso** [bijij/ViewImage#111]
The "Search by image" stuff doesn't look good now:

![kep](https://user-images.githubusercontent.com/4479090/37468553-a117cf7a-2863-11e8-9354-bfab36d7352b.png)

**Comment by needforsuv** [comment]
This was a bodged fix #109

**Comment by bijij** [comment]
I'll see if I can add the padding back sometime today.

**Comment by deuxsonic** [comment]
Is the XUL branch going to get the fixes?

**Comment by bijij** [comment]
@deuxsonic I'll be hopefully updating the XUL branch sometime this weekend

**Comment by bijij** [comment]
Fixed, will be rolling out new version now.
