### ISSUE TITLE
Userscript Not Working [Chrome/TamperMonkey]

### ISSUE THREAD

**Issue by DFNCTSC** [bijij/ViewImage#118]
Error via console:

ERROR: Execution of script 'View Image' failed! Cannot read property 'sync' of undefined
(anonymous) @ chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=c4dbaca4-ebe9-4bb3-8355-7d9e7c2d66f4:3

**Comment by DFNCTSC** [comment]
Just to be clear, the View Image extension is working, but the userscript isn't.

**Comment by bijij** [comment]
Hi, I applied some changes to the script today. can you please confirm this is still the case?

**Comment by DFNCTSC** [comment]
@bijij Updated to 1.9.3 and still the case.

New error via console:

Uncaught ReferenceError: localiseObject is not defined
at addLinks (userscript.html?id=c4dbaca4-ebe9-4bb3-8355-7d9e7c2d66f4:97)
at MutationObserver.eval (userscript.html?id=c4dbaca4-ebe9-4bb3-8355-7d9e7c2d66f4:146)
