### ISSUE TITLE
Google changed things again, button placement messed up

### ISSUE THREAD

**Issue by thinkpad4** [bijij/ViewImage#122]
@bijij  https://i.imgur.com/f5wA2uI.jpg  That happens when I click on any Google Image image.  It still works to get the images, just the layout is messed up

**Comment by asdgfd** [comment]
I'm not even getting that, today. On my end, Google image search has been completely revamped with pop-up results, result scrolling independent from the background, image thumbnails aren't clipped/trimmed to fit into orderly rows, etc.

**Comment by thinkpad4** [comment]
Strange, they must be pushing it to limited people to test it

**Comment by asdgfd** [comment]
I *really* hope it is only a test (and it fails). It is a horrible layout (at least, it is horrible on desktop... it might be ok on mobile, but I don't internet on mobile, so I don't know).

**Comment by bijij** [comment]
I can't see this layout myself.
so I can't do anything about it unfortunately.
Staggered roll-outs can be troublesome.

**Comment by filips123** [comment]
This is new layout:
![slika](https://user-images.githubusercontent.com/16626308/39062601-51f3cbe8-44c8-11e8-8ac2-b17f4ada6980.png)

**Comment by asdgfd** [comment]
filips123, Yep, that's the layout I got.

**Comment by bijij** [comment]
Without direct access to it I'm really not going to be able to do anything about it unfortunately.

Might need someone who has the new layout to develop a solution.
