### ISSUE TITLE
Question: right-clicking + "open image in new tab" usually works.

### ISSUE THREAD

**Issue by cygvis** [bijij/ViewImage#125]
I just realized something but I'm not sure how consistently it works as well as a dedicated "view image" button (like this extension provides).

Right-clicking on an image and clicking "open image in new tab" will usually take you to the original image on the destination site.

_**Does anybody know of any situations where this method **_wouldn't_** work the same as clicking "view image" button?**_

I still miss having the button and that's why I've used this extension but, honestly, this "right-click" method is a fairly convenient option (as long as I can remember to use it) which doesn't require me to install yet another Chrome extension.

Just wanted to point that out to anybody that sees this. Feel free to close this as it's not really an issue.

**Comment by MikeyTMan** [comment]
its always worked for me (Except on pintrest source pics) but its just easier for me to click a single button rather than right click and go down to view in new tab since view in new tab is at the bottom of my right click pop up
