### ISSUE TITLE
Add rel="noreferrer"

### ISSUE THREAD

**Issue by qsniyg** [bijij/ViewImage#129]
Would it be possible to add rel="noreferrer", or at least an option for it, to the "view image" links? It would be very helpful for websites that disable hotlinking via google.

**Comment by bijij** [comment]
I'll consider adding a toggle in the next release

**Comment by TallGuysFreeADMIN** [comment]
Adding noreferrer does not prevent the hotlinking message/image from appearing. The messages are usually also set to appear when there is no referrer at all ("blank")

To bypass a hotlink message, ensure you're on the message page, hold ctrl and click the reload icon in the browser. This will clear the cache (fetch a new version) AND pass the domain you're on (itself) as the referrer, which makes the server think you're legitimately loading the image.
