### ISSUE TITLE
View image button doesn't load or doesn't work

### ISSUE THREAD

**Issue by terrorist96** [bijij/ViewImage#130]
Hi.

First of all, I wanna say that I love this extension and it works great 99% of the time. The 1% of the time it doesn't work, the `View image` button does not appear, or if it does appear, it does not work. I have some examples:

https://www.google.com/search?biw=1396&bih=873&tbs=isz%3Al%2Cimgo%3A1&tbm=isch&sa=1&ei=7o7rWvXHC4ab8wWOvbngCQ&q=The+Coastal+Path+in+Brussels+%E2%80%93+The+Atomium&oq=The+Coastal+Path+in+Brussels+%E2%80%93+The+Atomium&gs_l=psy-ab.3...13050.23711.0.23878.6.6.0.0.0.0.240.703.2-3.3.0....0...1c.1.64.psy-ab..3.0.0....0.H5WgVzCBQDY#imgrc=c6lktJA6lnQQUM:

https://www.google.com/search?biw=1396&bih=873&tbs=imgo%3A1%2Cisz%3Al&tbm=isch&sa=1&ei=q4TrWtH6M8fSvATq-pioBg&q=salk+institute+panorama&oq=salk+institute+panorama&gs_l=psy-ab.3...667694.669464.0.669936.8.8.0.0.0.0.357.866.2-2j1.3.0....0...1c.1.64.psy-ab..5.0.0....0.WNNr3-Wc4qg#imgrc=kEgUGekET60j-M:

Both these selected images, the `View image` button did not appear when I initially found them. However, after reloading the page, they appear but do not work.

Edit: Another one
https://www.google.com/search?num=100&q=amazing+buildings+in+the+world&tbm=isch&tbs=simg:CAQSlwEJWMmWAbE7cxsaiwELEKjU2AQaBAgVCAMMCxCwjKcIGmIKYAgDEij9HZcN0h7QHowVjRW8DfgBlQ3PHuw45iroKqEo7TjgJ8Q23yr2Nd4qGjBBvv-q4uAQT6T_1zv10I_1eUoXPyosdpTOBO8JCIyeQIul0n0GsWDv-g-kikFx2y3jUgBAwLEI6u_1ggaCgoICAESBLolszsM,isz:l&sa=X&ved=0ahUKEwj8_uWmyuraAhWIs48KHa_kCX0Q2A4IKigE&biw=1396&bih=873#imgrc=VI38l0QBBDDpKM:

**Comment by keombre** [comment]
Hi!
I'm sorry to say, that those issues are unfixable. Google doesn't always supply the URL to the original image. I might hide the button, when the URL was not found, however as you've sad, this issue is still very uncommon.
