### ISSUE TITLE
View Image button issues in pre-quantum Firefox

### ISSUE THREAD

**Issue by jedikalimero** [bijij/ViewImage#142]
It seems the "**View Image**" button does not appear in Firefox **56.0.2** (Latest version before Quantum. I don't know about older versions or Quantum versions) when using the Add On default options.

It can be made to work again when the option '_**Show globe icon in "Save Image" button**_' is turned off, so it is not a big issue for me, but it is an indication that something is going wrong and could go worse in later updates.

All other tweaks seem to be working correctly.

**Comment by qsniyg** [comment]
This has been fixed in the Chrome version, but not the XUL version yet.
