### ISSUE TITLE
Google's new design of images broke this extension

### ISSUE THREAD

**Issue by anton31kah** [bijij/ViewImage#147]
[Here](https://i.imgur.com/BPpkBQB.jpg) is what I mean, I can't see the "view image" no more, nor the "search by image" now, will this be ever fixed?

**Comment by maturz** [comment]
Try this, not sure how long it will last but seems to work for now.

```
// ==UserScript==
// @name         Fix view image again
// @namespace    Fixviewimageagain
// @version      0.1
// @description  Fix view image again
// @author       You
// @include      http*://*.google.tld/search*tbm=isch*
// @grant        none
// ==/UserScript==

(function() {
    setInterval(() => {
        var objectsToFix = document.querySelectorAll('.rg_bx.rg_di.rg_el.ivg-i:not(.addedImageLink)'), c = objectsToFix.length;
        while(c--) {
            var realUrl = objectsToFix[c].innerHTML.match(/imgurl=([^&]+)/)[1];
            var inputLocation = objectsToFix[c].querySelectorAll('.nJGrxf.FnqxG')[0];
            try {
            inputLocation.innerHTML += '<a href="' + decodeURIComponent(realUrl) + '" style="position: absolute;right: 0;top: 0;">View image</a>';
            objectsToFix[c].className += " addedImageLink";
            } catch (err) {console.log('Failed with:' + objectsToFix[c])}
        }
    },500);
})();
```

**Comment by anton31kah** [comment]
thank you very much, they seem to have gone back to the old design and the extension works perfectly

**Comment by maturz** [comment]
Maybe you used a different computer or browser, it's common to do rollout to a few users at first. I'm currently getting both designs if I use two browsers (one where I'm logged in to a google account). So the new design will likely completely replace the old one soon.

**Comment by anton31kah** [comment]
Yeah you're right that happened many times with many websites in the past from what I remember, I'll add that script in Greasemonkey so I'll be prepared

**Comment by Scarecrow237** [comment]
It's still not working on Google Chrome due to the new image search design.  [Here ](https://imgur.com/uRbS4kE)is an image search page.  [Here ](https://imgur.com/XpD8RkN)is what I get when I select one image from that page.  There is no option to "View Picture" included anywhere.  I have no way of "going back" to the old image search design.

I also have no idea how to add the script above to the extension on my Google Chrome.

**Comment by maturz** [comment]
You need a userscript extension like [https://tampermonkey.net/](https://tampermonkey.net/) then you just copy the script and choose create a new script in Tampermonkey and paste the script there then save.

**Comment by Scarecrow237** [comment]
Ok, so I've added tampermonkey to chrome.  Added the Script, made sure it was enabled.  And still, the Google Image Search is using the new layout and not the old one, and there is no option to change to the old layout, OR "view image" option on the page.

**Comment by maturz** [comment]
Well might be difficult to fix if your new design isn't the same as mine I guess they could be running an A/B test to see which of two designs is better. This is what you should be seeing if the script is working:

<img width="481" alt="fix view again" src="https://user-images.githubusercontent.com/25877290/43680092-021ab780-9833-11e8-972c-972932fe7e21.png">

The first picture shows the script and the second shows what you should be seeing if the script is running when you visit the page. If it's not running then there is probably something wrong with the include url, if it is running but not working my first guess would be that there is something wrong with the selector. The selector for each image box in the script is ".rg_bx.rg_di.rg_el.ivg-i" but it could just as well be something else that is different which makes the script fail.
