### ISSUE TITLE
Extension Might Be Causing Incorrect Location Reporting

### ISSUE THREAD

**Issue by ghost** [bijij/ViewImage#148]
I believe this extension is causing a slight problem with incorrect location reporting. I had gotten the extension for Google Chrome, my preferred browser, so that I could have the view image and search by image features again, but a few days after I got it, my browser began to incorrectly report my location as somewhere in Jacksonville, Florida when I don't live there (I live in Tucker, Georgia). Although the extension does not cause the same problem on Firefox, when I removed the extension from Google Chrome the problem disappeared. This is frustrating because I want to have this extension on Google Chrome AND I want my Google Chrome browser to recognize my location as Tucker, Georgia, at the same time. Any suggestions as to how to make these work correctly? I'd like to know as soon as possible. Thanks.

**Comment by bijij** [comment]
This doesn't happen to me, if anyone else can confirm it happens i'll look into it.

**Comment by bijij** [comment]
Closing this as it's been over a year.
