### ISSUE TITLE
Not working on chrome for linux

### ISSUE THREAD

**Issue by LucaMoschella** [bijij/ViewImage#153]
Hello,
It is not working in chrome for linux.
![image](https://user-images.githubusercontent.com/11019190/44087325-c7bd4fdc-9fbf-11e8-8961-e5de6b78895f.png)

Version of chrome: Versione 68.0.3440.106 (Build ufficiale) (a 64 bit)

**Comment by sabitkamera** [comment]
Not working in Chrome for Windows too.
68.0.3440.106 (Official) (64 bit)

**Comment by bijij** [comment]
Hello, can you please confirm this is still the case?
Not sure if related to issue most people were experiencing.

**Comment by LucaMoschella** [comment]
Now It is working, both on linux and windows!

**Comment by sabitkamera** [comment]
Yes, it is working.
Windows, Chrome Official, 64 bit. Latest.
