### ISSUE TITLE
Chrome not showing View Image button

### ISSUE THREAD

**Issue by LoverIan** [bijij/ViewImage#154]
Chrome Version 68.0.3440.106 (Official Build) (64-bit) 
Plugin version 2

Today I woke up to the view image button suite that was provided by this plugin no longer functioning. While open image in a new tab via right click still functions, this is concerning if Google has updated with the intent to block out plugins like this.

I've been using this plugin since a day after it was put out, thank you so much for the tireless work you do, and thank you for how much it helps others.

**Comment by panhartstuff** [comment]
Same here, it's not working for me

**Comment by AquaVirus** [comment]
It's not working for me either. Using the same Chrome and Plugin version.

**Comment by JoshWay** [comment]
Same...  :(

Looks like Google changed something significant.  Bummer...

**Comment by sea-sunshine** [comment]
Same :( Ohhhhhh... Doesn’t work.

**Comment by EfronC** [comment]
Same :(

**Comment by eugeniots** [comment]
Não está funcionando aqui também. https://tsmix.com.br

**Comment by thaynenova** [comment]
thank you, i appreciate it. its wonderful to get such a prompt response.
wish 'blizzard' would do the same.

**Comment by ShamblerDK** [comment]
In the meantime, use this:
https://github.com/devunt/make-gis-great-again

It's still working as of 16/8-2018 at time 14:03.

**Comment by bijij** [comment]
Should be fixed in the release just pushed to app stores.
might take an hour or so to propagate.
