### ISSUE TITLE
Merge XUL and Chrome

### ISSUE THREAD

**Issue by qsniyg** [bijij/ViewImage#159]
Many of the changes seem to be going back and forth between the XUL and Chrome branches. Wouldn't it be easier to have them all on one master branch?

My idea is to have 3 folders: `xul`, `chrome`, and `common`. `common` would contain the content script, translations, etc. and `xul`/`chrome` would contain links to files held within `common`.

**Comment by filips123** [comment]
Folder or branch `chrome` should be named. `webextension` because it is not only for Chrome but for all browsers that support WebExtensions API.

**Comment by bijij** [comment]
renamed `chrome` back to `master`
