### ISSUE TITLE
Google UI redesign breaks functionality

### ISSUE THREAD

**Issue by ghost** [bijij/ViewImage#166]
This extension no longer functions on the new Google Image UI. I'm not too experienced with this otherwise I'd submit a PR.

**Comment by bijij** [comment]
Still stuck on the old one myself so supporting changes isn't really possible for me.

**Comment by qsniyg** [comment]
@bijij I fixed the problem in the PR I sent :) For some reason, Google reverted the redesign for me, so I'm currently unable to test anymore, but after the fix, it worked fine when it was enabled for me.

**Comment by h-h-h-h** [comment]
This is what it looks like for me:

![image](https://user-images.githubusercontent.com/13482553/48912332-96008180-ee75-11e8-9b10-980619fda68a.png)

`Bild ansehen` is German for `View Image`.

Those are the links:

- 2x correct image
- 1x wrong image A
- 3x wrong image B

**Comment by qsniyg** [comment]
@h-h-h-h Have you updated to the latest version? The PR I sent should have fixed that issue.

**Comment by h-h-h-h** [comment]
@qsniyg:

I have the latest version from addons.mozilla.org (v2.1).

I'll wait till your PR rolls out over the normal update channel. I'm currently back to the old design of Google Images anyway (it just happens without me doing anything).

**Comment by bijij** [comment]
I forgot to update the release Firefox version, sorry about that should be live in the next few hours

**Comment by h-h-h-h** [comment]
Yeah, it's still v2.1 on https://addons.mozilla.org/de/firefox/addon/view-image/.

**Comment by bijij** [comment]
Mozilla didn't approve without me verifying something and I missed the email. sorry bout that
