### ISSUE TITLE
[Bug] 2 view image buttons show

### ISSUE THREAD

**Issue by OrangutanGaming** [bijij/ViewImage#167]
When the addon is disabled:
![image](https://user-images.githubusercontent.com/18350092/50550534-6c9ff600-0c6a-11e9-8c7d-fa337063ff3d.png)

After enabling the addon:
![image](https://user-images.githubusercontent.com/18350092/50550539-7a557b80-0c6a-11e9-8c63-d8c63c665ecc.png)

After refreshing the page since the addon was enabled:
![image](https://user-images.githubusercontent.com/18350092/50550542-8d684b80-0c6a-11e9-825c-a0a255bf57ec.png)

**Comment by bijij** [comment]
Having trouble reproducing what browser is this?

**Comment by OrangutanGaming** [comment]
This was with Firefox Developer Edition, I've recently went back to Chrome, however, which does not seem to have the issue.

**Comment by bijij** [comment]
Thanks for the heads up I'll have a check on Firefox tomorrow.

**Comment by bijij** [comment]
Is this still occuring for you? i still was not able to repro.

**Comment by OrangutanGaming** [comment]
Seems to work fine now, might have fixed itself when the layout changed again
