### ISSUE TITLE
The build version vs source code is not same

### ISSUE THREAD

**Issue by jackTaw88** [bijij/ViewImage#173]
Hi,

I was looking around. I check the version dates here:

https://addons.mozilla.org/en/firefox/addon/view-image/versions/

And the source code comit dates:

https://github.com/bijij/ViewImage/commits/xul

- There is a "Version 2.1.1" On firefox web site released on Jan 1, 2019, the source code is updated last year (except locales/translations). but on release note writes: "fixes issues with redesign".

- also I see november 2018 on firefox web site. but on source code the last comit is june 2018. did you released the package after 3 months?

I will be happy if you can help me to understand how the build and release process goes.

Thank you

**Comment by bijij** [comment]
Hi, XUL branch is very halted.

Master has been updated incrementally and is the branch for the current firefox extension.

Major x.0.0 indicates a rebase of the underlying code.

Minor 0.x.0 indicates a change to the JS for bug fixes or feature additions

Macro 0.0.x indicates translation and other small changes.
