### ISSUE TITLE
Stopped working, update plox

### ISSUE THREAD

**Issue by CommanderPirx** [bijij/ViewImage#174]

**Comment by rahidz** [comment]
Yup, I keep getting a

>The previous page is sending you to (URL).
>If you do not want to visit that page, you can return to the previous page.

message when clicking on the image, instead of getting the image page.

**Comment by bijij** [comment]
Cannot repro myself. might need help in doing this.

**Comment by limewire** [comment]
same here, with the last google images update a 72 hours ago the extension is broken, the button disappear.
![image](https://user-images.githubusercontent.com/17796457/61178112-3c8fc300-a5bc-11e9-9e10-edca8aa67abb.png)

**Comment by bijij** [comment]
Google seems to have pushed a new design out for the images page, this new design does not work with the View Image extension.

I personally do not have access to this design, the googles images page i see is still the old one and as such cannot work on fixing View Image. 

I will need help on this,

Sorry for any inconvenience,

**Comment by Landcross** [comment]
What help do you need exactly? I don't know how Chrome extensions work, but I'd be happy to help where possible, because I really miss the button haha.

**Comment by JackOfSpade** [comment]
How are you accessing the old google images page?  All Google website have been updated to this new version?  If I could somehow use the old version and still get this extension to work, I would love to.

**Comment by JackOfSpade** [comment]
How are you accessing the old google images page? All Google website have been updated to this new version? If I could somehow use the old version and still get this extension to work, I would love to because my current software automation depends on this extension to work.

**Comment by Landcross** [comment]
I guess it's a staged rollout from Google, they almost always do it like that.

Up until 2 days ago I also had the old version and I didn't even know a new version existed. Then I reinstalled Windows (and Chrome) on one of my pcs and suddenly had the new version.

**Comment by limewire** [comment]
To get the new google image update, you need to Logout your Google Account and Login again with latest Google Chrome.

**Comment by bijij** [comment]
Logging in and out does not seem to work for me, still seeing the old design.

**Comment by limewire** [comment]
> Logging in and out does not seem to work for me, still seeing the old design.

Try in "Incognito Mode", go to:
https://www.google.ga   or
https://www.google.de

**Comment by bijij** [comment]
I was unsuccessful on Chrome and Firefox, but i found that the Chromium based Edge browser shows the new Google images design for me. so I'll get working on getting the theme to work on it.

**Comment by bijij** [comment]
I've just pushed a new version of the extension I'll be putting it up on the chrome/firefox stores in the next couple hours.

This update rewrites essentially the entire system, in my testing it seems to work just as well as previously as well as now working for the redesign.

If you find any instances where the old version worked but the new version does not please let me know.

Ta.
