### ISSUE TITLE
Buttons missing in new images layout

### ISSUE THREAD

**Issue by terrorist96** [bijij/ViewImage#181]
Similar to #161 

Search Google for image, either open result (All sizes) or click on a visually similar image.
`https://www.google.com/search?q=Canyonwoods+Drive&tbm=isch&source=iu&ictx=1&tbs=simg:CAEStAIJ1-YEoZYjTqMaqAILELCMpwgaYgpgCAMSKP0Utgr4FdEUwAr9FdUU_1xT8FL4KxjikKuY-uirlPrEqwCq1KrwqzTgaMFKaz9T2q91cUR0ZA-yd4W_1AxPpRPj0TFq9vVazVJ1d3XIWii4UIxsYnoWx9iSTUAiAEDAsQjq7-CBoKCggIARIEMl4EbgwLEJ3twQkaoAEKGQoGZXN0YXRl2qWI9gMLCgkvbS8wMzh0OF8KJQoSbGFuZHNjYXBlIGxpZ2h0aW5n2qWI9gMLCgkvbS8wOTBwYnIKJAoRc2VjdXJpdHkgbGlnaHRpbmfapYj2AwsKCS9tLzA3amIxYwoaCgdldmVuaW5n2qWI9gMLCgkvbS8wNG14MzIKGgoHbWFuc2lvbtqliPYDCwoJL20vMDJwdmJiDA&fir=zF8DJ6WBYLYLTM%253A%252CFzV-7_94IgS1pM%252C_&vet=1&usg=AI4_-kTVNPFJR3RCvIOCdBKjEyDnQkI2VA&sa=X&ved=2ahUKEwiZtb3vjPHjAhUnTd8KHSJfA9oQ9QEwAnoECAAQBA#imgrc=zF8DJ6WBYLYLTM:&vet=1`

![image](https://user-images.githubusercontent.com/12802056/62637197-fbfc3e80-b908-11e9-8b8b-7473b2ea1ebc.png)

**Comment by terrorist96** [comment]
But the `View Image` button **does** appear if I search via text and go to the images tab (but the `search by image` button is missing still).

`https://www.google.com/search?rlz=1C1GCEV_en&biw=1680&bih=903&tbm=isch&sa=1&ei=lfJKXenmM6uOggf0xbrwAg&q=test&oq=test&gs_l=img.3..0l10.12281.12582..12701...0.0..0.85.303.4......0....1..gws-wiz-img.......35i39j0i67.2GaVKFNgzr8&ved=&uact=5#imgrc=LLSqc5L4G3MOTM:`

![image](https://user-images.githubusercontent.com/12802056/62637370-50072300-b909-11e9-85aa-11c95d72eb2e.png)

**Comment by tolgabalci** [comment]
Some images have the View image globe button and some images do not.  Haven't found a pattern for which ones do and which ones do not.

**Comment by bijij** [comment]
@terrorist96 in the picture shown there the search by image link is just below where you circled.

as for the original issue post, google seems to be doing something different there where the sidebar section is loading multiple images at all stacked on top of each-other and hiding all the other images based on the one you clicked on.

Might take a while to find a solution which fixes that without breaking all the other implementations google has in place.

**Comment by bijij** [comment]
To add to this. if you just click around all the images on that page you linked at random eventually the view image button will begin appearing as expected.

**Comment by terrorist96** [comment]
> @terrorist96 in the picture shown there the search by image link is just below where you circled.
Where?
![image](https://user-images.githubusercontent.com/12802056/62743689-5385d180-ba11-11e9-8654-2371f23fafe2.png)

> To add to this. if you just click around all the images on that page you linked at random eventually the view image button will begin appearing as expected.

Can confirm this is true.

**Comment by bijij** [comment]
To the right of the "Images may be subject to copyright" it's just hyperlinked text rather than a button on the redesign for now.

**Comment by terrorist96** [comment]
Oh I see it now. But it's not there in the very first image I posted.

**Comment by terrorist96** [comment]
Here's another issue. After clicking around to get the buttons to appear, sometimes the links will be for other images. For example, I clicked the `Search by image` link for one picture but it opened a tab with another picture's search result instead.

**Comment by bijij** [comment]
This seems to have resolved itself with Google changing the layout again. Or at least has for me. Closing for now.

If you're having issues perhaps discuss in #188

**Comment by terrorist96** [comment]
It's more broken than before for me. Don't see the `View Image` or `search by image` links anywhere.
