### ISSUE TITLE
The "Search by image" feature not displaying on latest version of Google Images

### ISSUE THREAD

**Issue by gary-woods** [bijij/ViewImage#184]
Unfortunately, since Google Images interface was updated for a short while ago, the Search by Image button is not appearing. The View Image button is working though.

I am using the latest version of Firefox: 68.0.1

**Comment by mikadocat** [comment]
Can't you just Right-click>Context menu>Search Google for Image ?

**Comment by bijij** [comment]
Search by image should be appearing down beside the copyright information with the new design.

**Comment by mzso** [comment]
I don't see it.

**Comment by bijij** [comment]
![image](https://user-images.githubusercontent.com/8677174/68085209-359e0080-fe8a-11e9-8924-92ba81cb9232.png)

Should show up there as circled.

**Comment by mzso** [comment]
Well, I updated to the latest (View Image - 3.2.0, and now 3.2.2) in Firefox, but I only see the copyright text there.

Or where is that exactly? When I click on a thumbnail it doesn't look like that.

Oh, I see now. I use the Google Images Restored addon, to get GI more usable and this doesn't work with it.

**Comment by bijij** [comment]
When you click on a thumbnail might i ask what the site looks like for you? google images looks different for different people because google likes to test different designs.

**Comment by mzso** [comment]
Well, it looks like the old design, because of the aforementioned extension.

**Comment by mzso** [comment]
> When you click on a thumbnail might i ask what the site looks like for you? google images looks different for different people because google likes to test different designs.

@bijij  So ultimately it looks like this:
![kép](https://user-images.githubusercontent.com/4479090/68120079-c0bbdc80-ff04-11e9-9491-ca82c36d401d.png)

**Comment by mzso** [comment]
Anyay. It's unfortunate that I can't find a way to bring back the old appearance and the search by image link as well.

**Comment by bijij** [comment]
Can you link me to the extension? I'll have a try and adding the link back to it if you'd like.

**Comment by mzso** [comment]
This should be it:
https://addons.mozilla.org/en-US/firefox/addon/google-images-restored/

**Comment by needforsuv** [comment]
@bijij

that extension loads the full sized image, and when you used the view image button, IT WORKS!

This could definitely help issues
#201
#190
#188 
#131

You should definitely do a collab or something and enhance the extension

**Comment by bijij** [comment]
@needforsuv that extension does not work for me with the OCT19 design.
So might not be a perfect solution.

**Comment by mzso** [comment]
[**@bijij**](https://github.com/bijij) commented on [2019. nov. 7. 10:00 CET](https://github.com/bijij/ViewImage/issues/184#issuecomment-550986440 "2019-11-07T09:00:11Z - Replied by Github Reply Comments"):
> [@needforsuv](https://github.com/needforsuv) that extension does not work for me with the OCT19 design.  
> So might not be a perfect solution.

Annoying that google keeps changing things for the worse and ruining its own service. Taking away features, ruining layouts.

I still use the old sidebar tools (via an user style that I found) which is far more practical than the annoying bar that is hidden by default and you need to click multiple times to bring up a feature.
