### ISSUE TITLE
Userscript is broken

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [bijij/ViewImage#187]
Userscript v3.0.0 simply doesn't work. The "View image" and "Search by image" links are nowhere to be seen.
Tested in Firefox 69.0.1 + Voilentmonkey 2.11.2 and Waterfox 56.2.14 + Greasemonkey 3.17.
Firefox and Chromium extensions v3.0.3 work fine.
I have the new Google image search layout that displays large image and details on the right side of the screen.

**Comment by bijij** [comment]
This'll be fixed along with the main extension release in the next couple days, guessing Google's changed things.
