### ISSUE TITLE
Doesn't seem to be working at all right now

### ISSUE THREAD

**Issue by trlkly** [bijij/ViewImage#191]
None of the results on this page seem to have the option to view the image: https://www.google.com/search?q=Arrival+of+Everglow&tbm=isch

Unlike the previous bug, it does not seem to be restricted to larger images--even a 400px image included no "view image" link. 

I am running Chrome 78.0.3904.70 (Official Build) (32-bit). and version 3.0.4 of this extension.

**Comment by bijij** [comment]
Gonna mark as duplicate of #188 Seems google's messed with things again.
