### ISSUE TITLE
Removing Gecko ID from manifest

### ISSUE THREAD

**Issue by TotalCaesar659** [bijij/ViewImage#192]
@bijij Hello, why did you remove Gecko ID from manifest (https://github.com/bijij/ViewImage/commit/be1f425fc6107813988835d2d645cdf7302ddf56)? Is there any good reason for it?
I wanted to add View Image to Firefox for automatic startup after new installing (https://support.mozilla.org/en-US/kb/deploying-firefox-with-extensions), but now it doesn't have ID, so I have to add it manually, and it's not comfortable, unlike many other add-ons.

**Comment by bijij** [comment]
Removing gecko from the manifest simplified publishing to various webstores for me, as some *cough* Google will not accept a manifest with any keys it doesn't have in it's spec.

If this is causing issues for you I'll revert that now.

**Comment by bijij** [comment]
Release just pushed to AMO has the gecko ID in the manifest.
Future released will automatically include it.

Sorry about that.

**Comment by bijij** [comment]
That being said seems the extension is entirely non-functional for some people right now. so not sure if this'll be helpful to you straight away.

**Comment by TotalCaesar659** [comment]
Ah, I thought it may be deprecated or smth. Thank you very much for reverting, I'll wait for a fix.
