### ISSUE TITLE
Image linked is too little

### ISSUE THREAD

**Issue by gabri25ele** [bijij/ViewImage#195]
If I enable to Display Globe Icon, I see the link to see the image, but in the example
![sshot-1](https://user-images.githubusercontent.com/33927879/67638593-93f53d00-f8e6-11e9-85d0-f2f3bfc26efa.png)

the image size is 1707x2560, but if I click on the image, I see a miniature
![sshot-2](https://user-images.githubusercontent.com/33927879/67638614-d0c13400-f8e6-11e9-988d-cdd28f0df8b9.png)

**Comment by artquest** [comment]
Same here. But alternatively you can use right click on image context menu: "Open image in new tab".
Also I don't have "Search by Image" button next to "View Image", only as a context menu item.

**Comment by bijij** [comment]
This was caused by a quick fix I made when google made changes to the site.
New release coming out in the next few hours should fix this for you.
