### ISSUE TITLE
Stopped working in latest Chrome due to security policy?

### ISSUE THREAD

**Issue by patrickhlauke** [bijij/ViewImage#202]
Not sure when it happened exactly, but it seems that in the latest Chrome version there's been some change to security policy. The extension opens an about:blank new tab, but then nothing more happens. Error in the console along the lines of

```
Not allowed to navigate top frame to data URL: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxET...
```

**Comment by artquest** [comment]
Same here.
Chrome 78.0.3904.108

**Comment by lucasverra** [comment]
Firefox is all butter smooth 😅

**Comment by JAKill02** [comment]
Cent Browser ver. 3.9.2.45 based on Chrome 72.0.3626.121,dosen't work at all, so this is not due to Chrome version upddate, it's just Google doing some things

**Comment by Monirzadeh** [comment]
same happen in brave Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

**Comment by patrickhlauke** [comment]
> so this is not due to Chrome version upddate

well yes it's a chromium issue, not chrome per se.

**Comment by bijij** [comment]
Hi, changes recently made should hopefully fix this issue in most instances.

**Comment by patrickhlauke** [comment]
Sorry, coming in late to say thank you. Works like a charm again.
