### ISSUE TITLE
List of 193 other domains

### ISSUE THREAD

**Issue by lucasverra** [bijij/ViewImage#203]
**Is your feature request related to a problem? Please describe.**
i wish to have a clear view on the permission i give

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/11323803/69762658-38c79c00-116b-11ea-8fd0-c0a27567726a.png)

**Describe alternatives you've considered**
remove extension

**Additional context**
privacy is important

**Comment by bijij** [comment]
Hi there you can see a list of these domains here: https://github.com/bijij/ViewImage/blob/master/manifest.json#L41

It's essentially just google's different locale specific sites.
