### ISSUE TITLE
No longer directly viewing images on Google.

### ISSUE THREAD

**Issue by MeddyIka** [bijij/ViewImage#204]
I have found that, at least today (12/4/19), clicking the View Image option no longer brings up the actual image, but instead (possibly) the thumbnail image from Google itself. This is happening on the Firefox extension. 

I can search for any image, in this example I used "doggo". The image search itself is working, and I can click on an image and bring up all of the default options that Google provides in its half-bar menu. The View Image link/button appears as it should. Clicking the View Image, however, only opens up what SEEMS to be the Google icon, not the actual image. The URL to the image is very strange and very long. (Note that ANY search term in place of "doggo" has the same results.) It does not matter what site the image is HOSTED on. 

**APPEARANCE OF SEARCH PAGE AND SELECTED IMAGE OPTIONS**
![2238db5c855b1364093a41504b0f77ce](https://user-images.githubusercontent.com/58518866/70152080-903d9e80-167a-11ea-885f-88fb211d9560.png)

**WHAT HAPPENS WHEN I CLICK VIEW IMAGE**
![ba78f1b15ee5a895e1279d2bf0c343a0](https://user-images.githubusercontent.com/58518866/70152177-bd8a4c80-167a-11ea-883a-3b84d3931a10.png)

**EXAMPLE "URL"**
`data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAPDw8PDxAPEBAPEBIQEA8QDw8WDw8PFhEWFhgSFRYYHSggGBolGxUYIjIhJSkrLi4uGB8zODMsNygtLisBCgoKDg0OGxAQGy0lICU1LzUtLS0tLSsvLTUtNS81LS0rKy0tLS0tLS0vNS0tLS0tLS0tLS0tKy0tLSstLS0tLf/AABEIAJ8BPgMBIgACEQEDEQH/xAAbAAEBAAIDAQAAAAAAAAAAAAAAAQUGAgQHA//EAD0QAAIBAgQEAwUFBwIHAAAAAAABAgMRBAUSIQYxQVETYXEigZGhwQcjQrHRFDJSYsLh8JKiM0NTcoKy8f/EABkBAQADAQEAAAAAAAAAAAAAAAABAwQCBf/EACYRAAICAgIBBAIDAQAAAAAAAAABAgMEERIhMSJBUXEjMgUTM2H/2gAMAwEAAhEDEQA/APaiAgBSAhIABAAUgAOSBCgFKcSkAoIUAAAAAAAAAAAHzr1o04SnN2jCLlJ9opXbAPoDyaXGONlip1o1FGGu0MM7OOi+yk1+Jrn5npuUZjDFUYVobKV04vnCadpRfoyqu5Tei2dTitncABaVAAAAEAAIAAAQAFBAAUpAAUEAAABIIAACMhyOIBSAoBUAACgAApNSPhi6umLZh6ecw5Sdiiy+MHplsKnNbRn9a7lTNflmcFyd168jnDNlGN007K6K1l1+528eZngdTDY1T8jtJmlSTW0UNNdMoAJIBgeNajWDnBOzqzhBea1amvhFmeNO4/oVa3gxpaJQjr8ZSbVr6dLTXXZlORPjW2W0R5TR49Tr1P2udPzvu3s79T0DgXiZUK+Jw8/bjJKpFQa2mklL4q3wNbr5DSjNVpSlGcb2jGW8vZas37zhleFjSqOcXpd/Vy9XzZ5tmRr1R8noQo31LwezYLPKNXa7g+07K/vMjGafJp+jTPLMLjpX3s7DOOKp4Kk50U9bVuto3/E12/U6p/kW3qS39HNuAl3FnpOY5pQw0dVepCmv5nu/RGMyzi/BYmsqFKq3UlfSnCSvZX2v5JnjOKzVxjGviJzq1J/id3byS6I2j7Pk8TiaFZKypzk7tb6fDlfc1/3TbT9jN/VBJ7PWwAazKCAMAgBAClIACgAAoIACgEJAAIAGQEABUQIA5oEQAOQIUA6WbxvTdrp+XM8pzLNfCqSjL/Uml8j13FUtcHHutrHgP2i4GtGtKL2u9m7J+t0YsqtSabNWPNpNI7tbiC6/eV+jX9jjgs7qTcYwk7pNO26fkzVMu4WnOcXKpNx2vpb+B6rw7ktLD01oirre75vbuYLI1x8ds21uyXb6Rl8hzSemPiRlBcnKaXx5m0Rzigkrzfrpka1rXna/JnUxjSi972du92+hbVkSgtIrsx4ze2bfWz7DxV1NTfaN7nwlnEnHVGCitrOT+hr2R5e19/UVk+SfXzfY45jjfEkqaslfp1R1bmTS34OYYsG9eTPUM0qTc3dKmvxd7djUM6zpucmpNRXJNW/+mUxuLUKXhx67GAxmW64tysla7s3dvp6FUpSsj2zuKjCXSMZiZOqm0tle+/P4nSlUSTlB8r3adzDcU5biIRoVcK6rjC/i0qdSovavdPZp2autvI7eSVZVMGp17wqybTv+PfZ26XOXUlXy2dqxufHR3cBmL0vbVKUm+m3QyUEqqTqK/SzWzXVGIryo4WnF1KihraUIrecm1bZdd+9l5mSy/GUK0XOjUu4ycJwaalGa2aa7lLq0uSXRarNvi32YfOcjtNe17HOCdtP/AGt26HqH2Z4CMMPKooRje0I2bafWTTsr32+BrWCw6qXjJJromtj07K4KNCkoxUUoRtFKyWxvxJOcu/YxZSUV17naIAekYAQpACAMiAKUhQAUhQAAAAS4BIIAACMAAAAAFBEUApSFAB519oMIV8XSpf8AThefX2pPZW9PzPRJSsm3yW7PJKuLVTEVasnfXUlpb6+07fKxjzZ6hr5NWJHc9/Bzr0vCUdMU7q1tuSZ3cLiGkm3z6NcjG5nipWjyVpX5c/K58I1XLez5W6fTmeNr3PW37GwLMFe13t02Ot+0upLTpSjq35XfuvyMdKrop7reXe+x06OMSqRs3zvu/wBSVvRDSN1x+PjGnpb2ilZLZs194201La77W91joZliJVJxTls3fSmtvU69e97Lb8vyIluT2RFKKO/h8d41Scb77pepkadbVFxatJbSj9TUFiXRxF3ezd3Z/M2yooyVOsrvk778uq2NlS9jJb8nKpkMdOqDbcurk7L3GNxXD8L6Fsoq/nfuZTMs8jgsDVruMZ1IQT8PU7OUmla/bf4GpYT7RKOIrU4uhP76UKc3Fx1U23ZtW5xu17juzFk+4nNeTGPUjsYvhujjPZram6O0dDSdnzfmZ7JuGsPTpKlSgo2d5T/5kn0u/pyMzleBjTq1b9ErX6q7O6ppybi1boc11zcNSfXwTZZFT3Fd/JjcDl+iy3e/be5veHhphFdkjDZdQ1zvbZbu/czpux6lBNoyXWOXkAA0lBCFIwCMAAApAAcgQoAKQAFIykJAIUgBAUgAAAAKCgBFIUAx3EFZww1VrZuLSfrseP0rRqTptc94nr3EVPVh535JX+Z5VmNL71STs3dekTy85+pfR6OH+rJXp3i4+XMtFNJXs1bn1OxSpJxTs/7HZlg7RTtt9Dzltm1tI6eIjqSt0S9feYp034qe9r+/4mbnTsroPDJuMrO/kdHOzop/eNx5RjvtudXHV3eztZctkdycbTnJ3tsr77f53ODw+q76W96Guw30dHE0lUjGdt9r27mUyTMLWoVLaHylf91nQw0dEvDb2lyf83YyCyzVZp7+ZcpNeCqST8nZzvIZYmlKEJJtxtpk7KSta1+XIwnDPBkqGIhXq0beG7wTUbRl/EtPPlzdjcsrhNJKRmIy25fI9Gux8TBOPZMPDV+T7tnao4ZOWmCWp/LzOjPEze0bJem5sOSYTRDXLec92+y6IiElOXFCUeK2zuYXDqnFRXvfd9z6lIbEtGdvYIUgBGQpAAAAAEAACgAFBCgFABIJYFIACFIAAQqAKLAoAAAB18wp6qc494v8jyXMJLddU/e9z1+tG8WuV0eMY+ft1GndKcklt3e55uev1N+F7mUyql4jj05XNtlg46LWNa4XoPab6/kbzhKOpPyRGJUtNsjJsfLSNUxWVtbxWx86WDcdmnbysbNVjZtHGEIvZnUsVb2jmOQ9aZ59nNJxlLlufDLaqlzvt22ZsHF2DcNM1+5L2U/5rXt8PyNVwlTTLZ9eRhnHjJpm2L5RTMxiMFGSXxv1X6HYy1SXsy59Jd129Tjha+qSj3V9uVjL0cFt/lzqtbfRVN6XZ2sNTfXc7UY+RMNRZ3YU0j0YroxSfZ16VDyNjow0xiuyRj8DS1Sv0j/7djJltUEuziyW+gAC4rICkAIyFIAQAAAAoAAKAACgAFBIICkAIQ5AA4gtigEsUAAAoAOMldWPHcRl8li69J9Ksl7r3v8AA9kNI4hwUY5hrv8A8WEZteavH6GHOhuKf/TXhy1Jo++U5eo6UvKyNsoUtMUviY3KqF3fsvmZc0VQUYlFknJmEzSk1K/fc6NCV2d/iPEKCpLrJyXuSOllFLXL/NkcSfq0iYr07OHFuFUsukn0nCSfVe1zPLVBwlZvrz957LxTSvg6seiUfgpI8rrUE3ut72uYM30zX0bsR7g/sz+R4bVGO262Xc2aGWVbr2X8jrcDYVWc2v3Erer6/mbgW4lClDkynJtanxRqWKxHgNqas+x8I5omm157/ofXjGheon/L+phaNOyt5ld9k4ScfYsqhCUUze8mX3FN9ZJyfvf6HdPlg6einTj/AAwivkfY9SC1FIwTe5NkIUHRyQAAEIzkQA4shysLAEKWwAIUFAICgAAoJBAAACFABACgAAAAFABDT+JmnjodXGhG/lecjcTQ85rasxrK9tPhw9fuoy/qMea/QvtGnFXqf0bhlULUovrLc7h88NG0ILtFfkfQ1RWkZ35NI42xUliqULWjGjdPvKU2n8NJmuFJaqcpeaV/IwH2kJwq4Sp0mp036pqS/NmZ4Jqp0pxXRx+pki3/AHtM0yX4UzMZvR10Kse8H8tzymvH2refkewTjdNd1Y8kzOGmrKP8NRoo/kI/qy3CflG98Ex+4k+8kvgv7mxGtcCybw879Kn9KNlNeL/jEzZH+jNf4phvSfe6/wA+JgMsjqnTi971Ip/6jZuKKd6Kl/BL5NW/Q1fhmprxEV2qL5P+xkyl+VL5NOO/xt/B6CAD0zACFABAAAQFIAQFABCgAAAAAFABAcVItyQUAAAAAAAAAAAAEbI5AFuecZo746rO9vv5f7bQ/pPQpVbHm2Y5rUjXcP2LGT1VJ6pQw1Vxu5bS1Ws1a72exlyq3NJGiifBtnpdCd4RfeK/I53MJkOLqyw1Px4OnUSalBtN2Umk9u6SfvO865oT6KH5PhxFlscVh5QaTlH26flNJ2/Q1HgrNoU6jjKSTaaceqsbjLES6WNPxHBSqV5144qrRlObmvDp0rU781G69+9yiytualEthNKLjI36hiI1FeLTR5nxZDRi6se8lL4pP6m38N5JHBp/f1q7ts6zh7Pe2lK9/O5q3GcGsbKT/Goteijb6FOam6038l2I0pvRsP2f1L0q8b8pxfxT/Q2s0f7P8SlOvTfOajJf+N9vg/kbtqLcN7pRVkrVrMZxRf8AY69ldqKf+5bmkcIz8OvSv/HZ+r2+p6PiaSqQnB8pxcfirHlGFruFW11eErSt+GSe8X5ozZqcZxmX4rThKJ64DrYDFKrThNNe0t/U7J6Kaa2jE1p6AAJIBAAAQpAAAAAAACghQAAAD5qJbFBIAAAAAAAAAAAAJYjicgAfNxODpo+4sAdd0kcJUTtaTi0QDpTony0NGRaODgRobOlqaNZ4xp6vCqL8Knf0Sv8AVm3zga9xVkdTF0nTp1fBk04uely9mW0ltJWuupVdXzhxLKp8ZbNa4ZqVKVanUlylGUlG3OKsnvfn7S6HolLEKUVKLupK6fkaTDIccpxfjYdRgrR+7m3Zre61eS69zaMDR8KnCnz0K1+5xRW61o7unzezI+NbqaBxfh1TxDrwpzcJWqVPDpTn7XJ7QTbfJ8jc3I+Timd2wVi0ziuTg9o1TIOKFLX9ziaai/ZUqNRSl6Jq5v2X4p1aUKjjKDkr6ZJqS9U+V+fvOjT2O1CodQjx6Ik9nd1C5141DmpFhwfYHzUi6gDmQly3AAAJAABAAFyXAOQONxqAP//Z`

It SHOULD bring up, obviously, the direct image from whatever source it is hosted on (as long as the image still exists on the server.) Instead, it seems to be, as shown above, grabbing the Google Image icon rather than the direct image.

**I am using:**
Firefox version 71.0 (updated today, 12/4/2019.)
Latest version of the Extension, grabbed from the Firefox Add-on search.
Running on Windows 10.
I have no URL redirection extensions or userscripts enabled in this example. _Toggling off Tampermonkey, Ad Blocking, or disabling ALL addons does not change the behavior of the View Image button. Antivirus software is not interfering - I tried turning that off briefly as well._ But, for information, I am running Kaspersky version 19.0.0.1088(i).

I'd really love to see the extension working again, thank you for the hard work put into it!

**Comment by ThirtyWorse** [comment]
same on chrome

**Comment by Unknow0059** [comment]
It's a similar issue on Chrome, except I don't get to see the thumbnail. A window titled "Untitled" with a data url shows up, but no image.

**Comment by Chene-mou** [comment]
same issue

**Comment by artikandri** [comment]
Hello,
I just want to share that deleting **all cookies** works for me (30/12/2019). Im using the Firefox Dev Edition browser, ver 71.0 for 64-bit. It sure hurts to lost all the login session, but I can always log in back.

**Comment by DocHobo** [comment]
I am also having the same issue on firefox

**Comment by artikandri** [comment]
I am also having the same issue in Firefox Developer Ed. In my case, sometimes the plugin works, sometimes it returns the base64 image or the encrypted, smaller google image. Thankfully it works in incognito, but I havent found another workaround for this.

**Comment by weendigo** [comment]
I had this issue as well but now it seems fixed, pictures are opening correctly now.

**Comment by MrNotSoNice** [comment]
Same here.  I'm just getting a thumbnail.  I just noticed it today.  I was fine about a week ago.

**Comment by SeeDborg** [comment]
Same for me since yesterday. I'm on Firefox.

**Comment by bijij** [comment]
Hi, im merging these isues into one main thread for now, please use #207
