### ISSUE TITLE
Certain images do not have a "View Image" button.

### ISSUE THREAD

**Issue by salehio** [bijij/ViewImage#205]
**Describe the bug**
When I perform a reverse image search, I expect the results to have the 'View Image' button provided by the extension. For some images I reverse search, I do not see any 'View Image' button.

**To Reproduce**
1- Go to https://www.google.com/searchbyimage?&image_url=https://i.imgur.com/mv1K8UY.jpg
2- Click on the 'Large' under 'Find other sizes of this image".
![image](https://user-images.githubusercontent.com/12577679/71760442-976eec80-2e72-11ea-950e-c82a1888f49f.png)

3- Click on any of the two resulting images.
4- Observe the lack of a 'View Image' button.
![image](https://user-images.githubusercontent.com/12577679/71760453-ca18e500-2e72-11ea-9e21-4bba368471a2.png)

**Expected behavior**
I expected the images to have a 'View Image' button added by the script.

**System Information**
 - Chrome Version 79.0.3945.88 (Official Build) (64-bit)
 - Firefox 71.0 (64-bit)
 - v3.2.2 (win x86-64) - en

**Additional context**
I have validated that other images work fine, but some images do not.

**Comment by bijij** [comment]
Hi there, version 3.3.0 was releaed today please let me know if this fixes your issue.

**Comment by salehio** [comment]
Looks good. Thanks for the update!
