### ISSUE TITLE
Userscript is broken (again)

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [bijij/ViewImage#209]
**Describe the bug**
ViewImage userscript no longer links full-sized images, even when the full-sized image from the original source is being displayed on the search page by Google itself. It links thumbnails from https://encrypted-tbn0.gstatic.com/... instead.

**To Reproduce**
Install ViewImage userscript and try using its main functions.

**Expected behavior**
"View image" should open full-sized image from the source website.
"Search by image" should be using full-sized image for reverse search.

**System Information**
Firefox 73.0
Violentmonkey v2.12.7
ViewImage Userscript v3.2.2

**Additional context**
ViewImage browser extension v3.3.0 doesn't have this problem.

**Comment by yourduskquibbles** [comment]
> FYI for anyone else having trouble getting this to work on firefox with [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/).
> 
> You need to set `Default injection mode:` to `auto` under Violentmonkey `Settings` -> `Advanced` -> `General` and it should work again as google now sets a CSP script execution policy that blocks it from loading on the default Violentmonkey `page` injection mode.

From https://gist.github.com/saviorxzero98/88662a751b48cfeb90f22a61ca4567eb#gistcomment-3188797

**Comment by nbmrjuhneibkr** [comment]
I'd rather not change global settings in Violentmonkey to fix one script. Is it possible to apply this only to ViewImage?

**Comment by yourduskquibbles** [comment]
> I'd rather not change global settings in Violentmonkey to fix one script. Is it possible to apply this only to ViewImage?

I don't know the answer to that, maybe you can declare that in userscript header? Would have to investigate

**Comment by nbmrjuhneibkr** [comment]
This is still open, huh? It's partially fixed now, "View image" appears works correctly in v3.3.0, but "Search by image" is still missing.  
I'll close this one, since there is a separate issue for "Search by image".
