### ISSUE TITLE
"View Image" in new tab.

### ISSUE THREAD

**Issue by gvoze32** [bijij/ViewImage#21]
Please add new tab when click "view image", just like old google. Thanks.

**Comment by bijij** [comment]
The next upcoming release adds a setting which allows you to toggle this.
It's currently available for Firefox and should be live on Chrome in the next hour.

**Comment by gvoze32** [comment]
Thank you, but when you release the update?

**Comment by bijij** [comment]
It should be live now?

If you click the button here:

![chrome_2018-02-17_22-52-11](https://user-images.githubusercontent.com/8677174/36341144-6b4e6b7a-1435-11e8-90b0-2edd191747b6.png)

you should be able to toggle the setting.

**Comment by gvoze32** [comment]
How can i setting it on Firefox?

**Comment by bijij** [comment]
go to `about:addons`

and click options.

![firefox_2018-02-17_23-16-43](https://user-images.githubusercontent.com/8677174/36341358-aa362f6e-1438-11e8-9131-c3d58dd1b7ea.png)

you should see the toggle on that page.

![firefox_2018-02-17_23-17-46](https://user-images.githubusercontent.com/8677174/36341368-cc434f92-1438-11e8-8732-8cc1baf49ebb.png)

**Comment by gvoze32** [comment]
Woah, it's worked, thank you very much.
