### ISSUE TITLE
"Search by Image" doesn't show anymore on Firefox 55 (worked perfectly fine since a week ago)

### ISSUE THREAD

**Issue by Shendue** [bijij/ViewImage#210]
Pretty much what the title says.
"Search by image" doesn't show up anymore, it did work just fine a week ago.
"View Image" still works perfectly.

**Comment by Jagick** [comment]
I am also currently experiencing this issue.

**Comment by nbmrjuhneibkr** [comment]
Same issue, both in Firefox 81/Violentmonkey 2.12.7/View Image userscript 3.3.0 and in Chromium 85/View Image 3.3.1.

**Comment by bijij** [comment]
This should have been resolved with version 3.5.0
