### ISSUE TITLE
Only works with default options set

### ISSUE THREAD

**Issue by quamin** [bijij/ViewImage#214]
I can only get this to work with default options set, changing text or hiding referer/global image and button does not show.

- Win 7 
- Firefox 76.0.1

**Comment by needforsuv** [comment]
case VERSIONS.OCT19:
                viewImageButton.querySelector('.XeEBj.AJkoub').remove();
                break;


can confirm in chrome

content-script.js:191 Uncaught TypeError: Cannot read property 'remove' of null

**Comment by bijij** [comment]
Fixed with next version.
