### ISSUE TITLE
View Image is a very non-descriptive title if only connected to Google

### ISSUE THREAD

**Issue by PhoenixIV** [bijij/ViewImage#216]
Just saying. In my opinion "Google" should somehow be included in the title. I love this plugin!

**Comment by friendlytherapist** [comment]
if it was it would be removed

**Comment by ner00** [comment]
Probably not a good idea if you want it to be available on the Chrome web store.

**Comment by PhoenixIV** [comment]
When I searched for this plugin I searched for "View image google". It did not show with what seemed most obvious.

**Comment by PhoenixIV** [comment]
Please bear in mind that I added this issue after having massive problems finding this plugin with the Firefox Plugin Search Bar. Common search phrases like "Google show image" did not list this plugin.

**Comment by ner00** [comment]
> Please bear in mind that I added this issue after having massive problems finding this plugin with the Firefox Plugin Search Bar. Common search phrases like "Google show image" did not list this plugin.

Quick comment on this; I do agree with this from a logic standpoint, but I think that the difficulty in finding the extension in this particular case is an issue with the search engine in general or user preferences. I replicated the search and it came in 6th place, all other 5 extensions had Google on their title despite having poor ratings and a few hundred downloads. Switching the ordering for top rated overshadows this extension with others that don't even have any of those words in their title. Using the "most users" order brings it to first place though, which seems to indicate that most people have found what they we're looking for with intent,
