### ISSUE TITLE
When the "Show globe icon" option is disabled, the "View Picture" button disappears

### ISSUE THREAD

**Issue by ghost** [bijij/ViewImage#221]
**Describe the bug**
Disabling the "Show globe icon" option removes the "View Image" button completely.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
The globe icon should be hidden, not the button.

**Screenshots**
<details><summary>When the "Show globe icon" option is enable:</summary>

![www google com](https://user-images.githubusercontent.com/34379403/90348248-d8042a80-e03d-11ea-9e83-c172340808b6.png)

</details>

<details><summary>When disable:</summary>

![v1](https://user-images.githubusercontent.com/34379403/90348262-e7837380-e03d-11ea-8ba8-09d5e86d8132.png)

</details>

**System Information**
 - Browser [Chrome 84]
 - Version [v3.3.1 (win x86-64) - tr]

**Additional context**

**Comment by nbmrjuhneibkr** [comment]
Can confirm, same issue in Chromium 85.

**Comment by bijij** [comment]
This will be fixed with version 3.5.1
