### ISSUE TITLE
Often does not work, adds a hefty base64 link which only decodes into a small image

### ISSUE THREAD

**Issue by mzso** [bijij/ViewImage#224]
**Describe the bug**
Doesn't linke the image with the claimed size. Only links a tiny image, and even that with a wacky data link, which when I hover the button covers half the screen.
**To Reproduce**
Check the image [here](https://www.google.com/search?as_st=y&tbm=isch&hl=en&as_q=grosjean+crash&as_epq=&as_oq=&as_eq=&cr=&as_sitesearch=&safe=images&tbs=isz:lt,islt:2mp#imgrc=MGWTD6kR9KD_2M) (until the link breaks)

**Expected behavior**
Should link

**Screenshots**
![kép](https://user-images.githubusercontent.com/4479090/100549696-cc4b1580-3274-11eb-8325-ad4c2e0b66b3.png)

**System Information**
 - Browser FF83
 - Version 3.3.1

**Additional context**

**Comment by bijij** [comment]
I don't think there's much i'll be able to do with images which google passes base64 data for unfortunately.
Though I think i improved attempting to fetch the URLs from elsewhere so this may be resolved.

**Comment by mzso** [comment]
[**@bijij**](https://github.com/bijij) commented on [2021. aug. 8. 01:46 CEST](https://github.com/bijij/ViewImage/issues/224#issuecomment-894719236 "2021-08-07T23:46:36Z - Replied by Github Reply Comments"):
> I don't think there's much i'll be able to do with images which google passes base64 data for unfortunately.  
> Though I think i improved attempting to fetch the URLs from elsewhere so this may be resolved.

Well, it seems like for the example I provided the view image button is not present at all. I can only visit the page.
