### ISSUE TITLE
Restore the ability to view image dimensions

### ISSUE THREAD

**Issue by elenderg** [bijij/ViewImage#228]
In August 2020, we saw Google making the move of adding a side panel for results and allowing users the option of shopping through the Images as well. Continuing with the subtle changes again, Google first removed the feature to filter results by sizes and now users will also not be able to see dimensions upon hovering over the images on the main results page.

Getting to know the size of the image by hovering over to the bottom left corner has been an easier way to find out the photo right of your choice. By now, it had even eliminated the need of using Tools and refining images for the correct size for many of the non-technical users.

But unfortunately, knowing the dimension of every picture won’t remain that easy as Google removed the feature from the desktop search result page.

**Comment by tsuliwaensis** [comment]
This is a duplicate of https://github.com/bijij/ViewImage/issues/211

**Comment by elenderg** [comment]
Thanks

**Comment by elenderg** [comment]
Thanks
