### ISSUE TITLE
Request for XUL Version

### ISSUE THREAD

**Issue by THEtomaso** [bijij/ViewImage#23]
Any chance of providing an XUL/XPCOM version, for Firefox legacy browsers, like 'Firefox ESR', 'Pale Moon' and 'SeaMonkey'?

**Comment by asdgfd** [comment]
I'm using 54.0.1 (32-bit) and it seems to be working fine on this version.

**Comment by bijij** [comment]
https://github.com/bijij/ViewImage/releases/tag/1.0

XUL Version.
