### ISSUE TITLE
Publish your extension to Microsoft Edge Add-ons website

### ISSUE THREAD

**Issue by sonakshimore** [bijij/ViewImage#230]
Microsoft Edge is the second most used browser on the web, making the browsing experience more flexible, offering many more services for users and optimized for Windows devices.

Microsoft Edge supports Chromium extensions, and you can publish your extensions to Microsoft Edge Add-ons website with minimal code changes. Find out more [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension).

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team). 

Let me know if this was helpful. I am happy to help you with more details.

**Comment by bijij** [comment]
Hi there, I'll take a look at getting the extension onto the Microsoft add-ons site this week!

**Comment by bijij** [comment]
Hi there, I last week added the extension to the MS store, waiting for microsoft to approve it at the moment, i'll close this for now but link once i've head back from ms.
