### ISSUE TITLE
Not Working in Firefox 90.0.2 or Chrome 94.0.4590.2

### ISSUE THREAD

**Issue by adanvdo** [bijij/ViewImage#231]
The add-on is no longer working in Firefox 90.0.2 or Chrome Version 94.0.4590.2 (Official Build) canary (64-bit)

On google image search, only the "Visit" button is shown when previewing an image.

![2021-07-29_20-30-06](https://user-images.githubusercontent.com/26498008/127582104-88dfc263-8d03-49ad-bf07-ab1ddf9ff3ac.png)

Windows 10 x64
Firefox 90.0.2
Chrome Version 94.0.4590.2 (Official Build) canary (64-bit)

**Comment by nicolaasjan** [comment]
I can confirm this issue.
It would be nice if it can be fixed (a lot of bad reviews lately...).

**Comment by theshindigg** [comment]
I'm on chrome 92.0.4515.107, and have the same issue

**Comment by devilbear** [comment]
I run several versions of both Firefox and Chrome for testing purposes and can confirm this is happening in all versions I have of both Firefox and Chrome, even as far back as Firefox Developer Edition 56 and Chrome 66.0.3359.139 - as well as the latest versions, of course, but others already mentioned those.

**Comment by ner00** [comment]
Same here, Firefox 90.0.2 (64-bit), Win10

**Comment by bijij** [comment]
Hi, I've currently not got access to a computer but I've attempted a fix from mobile, no way to test unfortunately.

I've pushed it out to web stores, hopefully it resolves the issues.

If not I can hopefully have a fix out in the next 12 hours, PRs always welcome though.

**Comment by nicolaasjan** [comment]
> Hi, I've currently not got access to a computer but I've attempted a fix from mobile, no way to test unfortunately.
> 
> I've pushed it out to web stores, hopefully it resolves the issues.
> 
> If not I can hopefully have a fix out in the next 12 hours, PRs always welcome though.

Thanks!
Just got the update in Firefox 90.0.2 and it works again:

![screenshot1](https://user-images.githubusercontent.com/14093220/127763917-1f21db23-7940-427f-9e6e-85e60eae1cd2.png)

**Comment by bijij** [comment]
Update, chrome rejected the most recent update from their store. 

![Screenshot_20210802-032303](https://user-images.githubusercontent.com/8677174/127779964-a42714ee-1da7-4a9b-9e1a-ecf838063e35.png)

I am unsure if this is evidence that the extension fix did not work for that reviewer, or a blatant attempt by Google to stop this extension from reaching the store.

I'll re-release to the chrome web store today.

**Comment by davidtderrick** [comment]
I suspect the latter!

**Comment by bijij** [comment]
Personally, I'm suspecting the reviewer couldn't see a "search by image" button, which I am aware does not appear for some users at the moment and rejected the application.

I've temporarily resubmitted a version which omits references to this feature from the application, I'm hoping tomorrow I can release a version with the feature fully working again, at least for users who see the current google image results page.

**Comment by davidtderrick** [comment]
It's working fine now for me on Firefox 91.0b9 (64-bit). Thank you.

**Comment by adanvdo** [comment]
can confirm working on Firefox 90.0.2 (64-bit)
still not working in chrome though

**Comment by bijij** [comment]
The chrome update has been pending a review from Google for the past 10 hours, I'll provide another update when I hear from Google.

**Comment by win98se** [comment]
Didn't work on Edge 92.0.902.62 using [Userscript version](https://gist.github.com/bijij/58cc8cfc859331e4cf80210528a7b255), changing [line 127](https://gist.github.com/bijij/58cc8cfc859331e4cf80210528a7b255#file-viewimage-user-js-L127) to `visitButton = container.querySelector('.ZsbmCf[href], a.J2oL9c');` works. (As in [changelog](https://github.com/bijij/ViewImage/compare/v3.4.1...v3.4.3))

**Comment by absay** [comment]
Still doesn't work on my end, FF 90.0.2 64-bit.

Tried to reinstall and still no luck.

**Comment by devilbear** [comment]
It worked for me in all versions of Firefox right after the update went live... but now it's once again not working. I think Google changed the element again overnight...?

**Comment by davidtderrick** [comment]
Oh wow. Now it has stopped working again for me too in Firefox 91.0b9 (64-bit).

**Comment by ner00** [comment]
> I think Google changed the element again overnight...?

This is improbable, I'm using the unchanged userscript mentioned above (https://github.com/bijij/ViewImage/issues/231#issuecomment-890337040) and it still works fine.

**Comment by bijij** [comment]
> This is improbable, I'm using the unchanged userscript mentioned above ([#231 (comment)](https://github.com/bijij/ViewImage/issues/231#issuecomment-890337040)) and it still works fine.

Google has a habit of using a different DOM for different people, it's possible that a 3rd new version rolled out today I need to accommodate.

**Comment by ner00** [comment]
> Google has a habit of using a different DOM for different people

The thing is that the ViewImage extension don't work for me either, nor does its userscript version, but the other usescript I linked works all the same since 3 days ago. This means that Google changed something else, but the other userscript can cope with it while ViewImage cannot.

**Comment by bijij** [comment]
> The thing is that the ViewImage extension don't work for me either, nor does its userscript version, but the other usescript I linked works all the same since 3 days ago. This means that Google changed something else, but the other userscript can cope with it while ViewImage cannot.

are you on chrome or FF?
The chrome webstore version is out of date because google is seemingly leving it in pending limbo.

**Comment by ner00** [comment]
> are you on chrome or FF?

FF 90.0.2
I'm looking at both codes, but I'm afraid I don't have enough knowledge to spot what makes one work over the other.

**Comment by devilbear** [comment]
Of interest: the linked userscript doesn't seem to be working for me in Firefox 56 (Developer Edition) or Firefox 90 (also Developer Edition). Once I saw it won't work in either of those on my end, I didn't bother checking the versions in between, but I assume it's the whole "different DOM" issue at play.

**Comment by ner00** [comment]
> the linked userscript doesn't seem to be working for me

Yeah, it's really weird, for me the `gis-vib.user.js` script works with Tampermonkey in Firefox 90.0.2 (Standard), Chrome 92.0.4515.131 (Standard), and Tor Browser 10.5.2 (Firefox 78.12.0esr). I tried in incognito and... well, Tor.

**Comment by quoid** [comment]
I'm using the userscript through my [manager](https://github.com/quoid/userscripts) in Safari. The newest (and previous) stopped working.

To get it to working I changed:

```js
viewImageButtonText = viewImageButton.querySelector('.pM4Snf');
```
to

```js
viewImageButtonText = viewImageButton.querySelector('span');
```

I believe the reason it was failing for me was that it the userscript reckons the `version` is `OCT19`, so it targets the `.pM4Snf` element, which is `null`. That breaks the functionality that adds the button. It's not throwing an error in the console perhaps because it is not injected into the page context due to the strict CSP?

The class of the `span` element in the button right now seems to be `KSvtLc`, but I am targetting the span element in case that class is dynamic or changes soon.

Also, my userscript manager doesn't, yet, support `.tld` so I need to change the `@include` values to:

```js
// @include         http*://*.google.*/search*tbm=isch*
// @include         http*://*.google.*/imgres*
```

**Comment by devilbear** [comment]
I installed this extension's userscript (as opposed to the one linked in a comment) and made the suggested changes above and it didn't work for me. However, I changed FEB18 and JUL19 the same way - replacing the class with span, and this seemed to fix the userscript for me. I also had to change the .tld to * as described.

**Comment by bijij** [comment]
I'll be releasing a newer version of the extension today which hopefully fixes is this for most if not all users.

Google once again rejected the extension for the same reason as before, so chrome is still stuck a version behind for now.

Hoping an updated version will fix that.

**Comment by absay** [comment]
@bijij Thanks for the hard work. Working with Google's stuff can be a true PITA, so having fixes and knowing this project is still maintained is always appreciated.

By the way, will the fix include the "Search by image" link/button to work again? It's been missing from quite some time now, and it's one of the things that I found most appealing when I installed this.

**Comment by bijij** [comment]
![image](https://user-images.githubusercontent.com/8677174/127958753-ecb5f497-fb6e-4191-aa5a-f393fd1d62cc.png)
I've just published v3.5.0 to AMO / Chrome webstore, pending their approval.

At least for me this reinstates both the view image and search by image buttons for the new google images DOM.
I'll be looking into removing reliance on hardcoded classnames from now on to reduce the chances of this occuring.

**Comment by devilbear** [comment]
Thanks so much for your hard work on this! Just updated the extension in Firefox (tested 56 & 90 Developer Editions) and it's working now.

**Comment by xscd** [comment]
@bijij could you update the userscript version too? Thanks. https://gist.github.com/bijij/58cc8cfc859331e4cf80210528a7b255

**Comment by ctwhome** [comment]
it seems to not be approved yet, that is a pity. thanks for the work

**Comment by BL4CKBL4D3** [comment]
Hi, the solution is really simple:
1.- Download this and extract it: https://github.com/bijij/ViewImage/archive/refs/heads/master.zip
2.- Go to chrome://extensions/ and enable Developer mode
3.- Click on "Upload unzipped" and select the extracted folder of the previously downloaded file

Support screenshot:
![image](https://user-images.githubusercontent.com/88482421/128317498-1a6e4a91-ea91-47fa-ab00-de6b5d473af4.png)

And that's it
View Image 3.5.0
Successfully installed

**Comment by nicolaasjan** [comment]
@BL4CKBL4D3
It works that way, however I get the error:
`Unrecognized manifest key 'browser_specific_settings'.`: 

```json
    "browser_specific_settings": {
        "gecko": {
            "id": "{287dcf75-bec6-4eec-b4f6-71948a2eea29}"
        }
    },
```

**Comment by nicolaasjan** [comment]
Just got the 3.5.0 update from the Chrome Web Store.

**Comment by adanvdo** [comment]
This is now working for me in both Chrome Version 92.0.4515.131 (Official Build) (64-bit) and Firefox 90.0.2 (64-bit)
I'm going to close this issue
