### ISSUE TITLE
Search image with Google Lens

### ISSUE THREAD

**Issue by mauricioakito** [bijij/ViewImage#232]
**Describe the bug**
Google has override the default option while using this wonderful plugin with a Google Lens search engine.

**To Reproduce**
Go to a photo that you want to search on Google Images and right-click on it.

**Expected behavior**
I believe that the users expect the old funcionality back and running

**Screenshots**
This is an example of what it renders (it is in portuguese)
https://ibb.co/mvKGx99

**System Information**
 - Chrome
 - Version 96.0.4664.93

**Comment by bijij** [comment]
It's not possible to override the right click button but I can add one using ViewImage sure.

**Comment by bijij** [comment]
I've released version 3.6.0 which adds in this functionality, It's live for Firefox but waiting on approval from google before it'll be available.

Closing
