### ISSUE TITLE
Remove 'Search by Image' in right click menu

### ISSUE THREAD

**Issue by deusexcalamus** [bijij/ViewImage#233]
**Is your feature request related to a problem? Please describe.**
Extension updated today and added an (unwanted) entry to my right click menu.

**Describe the solution you'd like**
I want the ability to remove this item. I already have (better) extensions for performing image searches in the way that this tries to implement, I don't need it to try and reinvent the wheel. I only want the extension to provide the features that it says it does, namely restoring the view image and search by image items on Google Image results pages, nothing more, nothing less.

In the meantime, I'll be reverting to the previous version of the extension and disabling automatic updates.

**Comment by SupDos** [comment]
yeah, same here. already have Image Search Options for this and couldn't find anything in the extension options to remove the context menu

**Comment by bijij** [comment]
This will be coming in the next update (v3.6.1) which i've just released now.

**Comment by onmyouji** [comment]
> This will be coming in the next update (v3.6.1) which i've just released now.

Is v3.6.1 also going to get released on Chrome Web Store?

**Comment by bijij** [comment]
Google as of like 2 days ago approved v3.6.0 so given their speed hopefully before the end of the month.
