### ISSUE TITLE
"Search by Image" context menu bugs

### ISSUE THREAD

**Issue by ITL71** [bijij/ViewImage#235]
1. It opens on the same page and not in a new tab 
2. There should be a toggle option for this feature in the settings page

**Comment by bijij** [comment]
Version 3.6.1 add this functionality, it was pushed to google / Mozilla webstores 2 weeks ago.
I am yet to have this update approved by Google however, hopefully some time next week.

**Comment by ITL71** [comment]
> Version 3.6.1 adds this functionality, it was pushed to google / Mozilla webstores 2 weeks ago. I am yet to have this update approved by Google however, hopefully some time next week.

I just wanted to add:

3. It asks for additional permissions every time you use this feature

hope it will be fixed too, thanks for the quick reply
