### ISSUE TITLE
"Open in new tab" doesn't open in new tab

### ISSUE THREAD

**Issue by o-r-i-z-u-r-u** [bijij/ViewImage#238]
Running Brave 1.36.109 Chromium: 99.0.4844.51

Any suggestions?

**Comment by o-r-i-z-u-r-u** [comment]
By the way I'm anticipating a resurgence / renewed interest in this extension now that Chrome/Chromium browsers seem to be defaulting to "search using Google Lens" for images in the right-click context menu

**Comment by FeBe95** [comment]
Had the same problem with Firefox 98.
Went into debugging and found this piece of code:
```JavaScript
chrome.contextMenus.onClicked.addListener(
    (info, tab) => {
        // [...]
        if (info.menuItemId === 'ViewImage-SearchByImage') {
            chrome.permissions.request({
                permissions: ['tabs'],
                origins: [tab.url],
            }, (granted) => {
                if (granted) {
                    // [...]
```
For me, the `tabs` permission wasn't granted in my extension settings (`about:addons` in Firefox):

![grafik](https://user-images.githubusercontent.com/7470739/159820882-ffd3f5f5-33ce-4513-a574-2bd84a674319.png)

Enabling both options fixed the issue for me.

**Comment by TinyWilll** [comment]
> For me, the `tabs` permission wasn't granted in my extension settings (`about:addons` in Firefox):
> 
> ![grafik](https://user-images.githubusercontent.com/7470739/159820882-ffd3f5f5-33ce-4513-a574-2bd84a674319.png)
> 
> Enabling both options fixed the issue for me.

thank you for this, i was looking for so long online until i came across this solution
