### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by MaskyS** [bijij/ViewImage#24]
I was originally creating this for a friend who was making the same extension, but you guys beat him to it before he even started :) Maybe you'd like to use this logo?
![128x128](https://user-images.githubusercontent.com/23234883/36342783-d055327e-141c-11e8-8572-8f3738a9e33c.png)

**Comment by UNREALWINS** [comment]
I like the original one.

**Comment by bijij** [comment]
Hi, I'll likely be keeping the current logo as I've already changed the logo in the two days this extension has been available. So I'd like to keep come consistency.
