### ISSUE TITLE
No Longer Working on Firefox.

### ISSUE THREAD

**Issue by ThomasEricB** [bijij/ViewImage#266]
When choosing to view image, it loads the low quality version.

**Comment by ruboard** [comment]
confirm

**Comment by ner00** [comment]
Is it just Firefox though? It seems to be the same in all browsers.

This may not be an issue with the extension though. In some cases, Google doesn't seem to be grabbing URL at all, instead it just embeds a base64 miniature, in which case I don't think there is anything that can be done to get the URL short of crawling the target page. Here is an example when it works fine: [https://www.google.com/search?q=wikimedia+moon&source=lnms&tbm=isch#imgrc=e0MOONwtisYikM](https://www.google.com/search?q=wikimedia+moon&source=lnms&tbm=isch#imgrc=e0MOONwtisYikM)

If you inspect the image element, you can see the original target image, which is the same that is opened by the extension's button: [https://upload.wikimedia.org/wikipedia/commons/e/e1/FullMoon2010.jpg](https://upload.wikimedia.org/wikipedia/commons/e/e1/FullMoon2010.jpg)

In other instances, the result shows a bigger resolution info than the actual image embedded, and if you inspect the image element you'll not find any URL to the full sized image. Not sure if/when Google changed the way they crawl target images but it seems that it did change and a workaround might not be possible this time around.

**Comment by vladimirgluten** [comment]
I think this addon might be dead.  No update in almost a year.  Shame, really, it worked great when it worked, but now it's completely broken, no "view image" button appears in either browser
