### ISSUE TITLE
stop working from chrome v111.0.5563.64 windows 11 x64

### ISSUE THREAD

**Issue by bigodon** [bijij/ViewImage#267]
**Describe the bug**
plugin is loaded but not given the image anymore

**System Information**
 - Browser Chrome x64 for windows
 - Version 111.0.5563.64

**Comment by bijij** [comment]
Hi there,

If possible can you open the chrome devtools window and tell me if any errors are printed when refreshing the browser window?

Unfortunately the extension is still working for me so I can't debug this issue at this time.

**Comment by javaskript** [comment]
Same issue here (using Edge 111.0.1661.44). No view image button, but plugin is loaded, no errors in devtools. Stopped working around a week ago.

**Comment by ner00** [comment]
Tested just now, with Edge, and it works. 
As previously mentioned, it appears that Google made some changes but aren't affecting everyone. Some even reported not working for the best part of a week or two and the starting working again out of the blue: https://github.com/bijij/ViewImage/issues/254#issuecomment-1463120193

**Comment by llamasoft** [comment]
In my situation, it looks like the [October 19th](https://github.com/bijij/ViewImage/blob/5ae7163ffb156155da22674f5969c1ca04e93cce/js/content-script.js#L67-L71) logic no longer selects the image.
The container selection logic using `tvh9oe` still works, but the image itself has class `iPVvYb`.  The other classes, `r48jcc` and `pT0Scc` work, but don't uniquely identify the image.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/4632450/230674375-f1648691-1c21-4218-bac8-bf22c8c98bec.png">

Just in case it's relevant, I'm on Chrome 111.0.5563.146 for MacOS with the dark theme enabled.  On my Windows machine this extension still works correctly.

**Comment by ner00** [comment]
@llamasoft This in particular was referenced in an earlier post on another issue here: https://github.com/bijij/ViewImage/issues/268#issuecomment-1475544461

Temporary workaround possible using this: https://github.com/bijij/ViewImage/issues/268#issuecomment-1476294452

**Comment by adanvdo** [comment]
Hasnt worked in a while for me. Currently on chrome Version 112.0.5615.122 (Official Build) (64-bit)

**Comment by piranna** [comment]
It doesn't works for me since about 1 month ago, CHrome 112.0.5615.165 on Ubuntu 22.10 here. My system is configured in spanish, but I'm accessing from UAE, where there's a gubernamental firewall that force enable the SafeSearch, in case that affects. Using a VPN does no difference.

**Comment by igarca** [comment]
Same here:(

**Comment by igarca** [comment]
Works perfectly on Chrome. It's a super useful extension. Thanks!!!!

**Comment by mzso** [comment]
[**@bijij**](https://github.com/bijij) commented on [May 22, 2023, 3:58 PM GMT+2](https://github.com/bijij/ViewImage/issues/267#issuecomment-1557271201 "2023-05-22T13:58:39Z - Replied by Github Reply Comments"):
> Hi all, I've just released a new update.  
> It's rolled out to chrome and hopefully should be available on Firefox soon.
> 
> Thanks for your patience.

Is the "search by image" button/link abandoned? It's still in the settings but I haven't seen it in a good while.

**Comment by ner00** [comment]
> Is the "search by image" button/link abandoned? It's still in the settings but I haven't seen it in a good while.

Personally, it only seems to work on Chrome (and possibly Chromium-based browsers). It doesn't work in Firefox, but given that Google images includes a camera button in the lower-left side of every image, it serves the same purpose so it's not an issue I don't think.
