### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by masdkm2149** [bijij/ViewImage#27]
One of the most used features by myself on google was the "More sizes" option that would list all other sizes of the image, along with the websites they were located on. It was extremely helpful in finding the highest quality version of the image along with having a link to all sites which have it in use. 

Can this be done? Thanks!

Edit: 
From trying to figure out how it would be done myself, it appears all you would need to do here is put in the "simg" string
https://www.google.com/search?tbm=isch&tbs=simg:(A bunch of characters here)

**Comment by asdgfd** [comment]
I am still seeing the "more sizes" and "all sizes" options when doing a search. Doesn't look like (from my side) that these were removed.

**Comment by jll123567** [comment]
I can't seem to find the more or all sizes button. I'm on windows, using chrome, in the US btw.

**Comment by bijij** [comment]
Clicking the "search by image" button, 
![chrome_2018-02-18_16-55-31](https://user-images.githubusercontent.com/8677174/36349187-bef533ac-14cc-11e8-9831-c8a91c550391.png)

Then clicking all sizes will take you to that page.
I might think about adding a direct link in the future.
