### ISSUE TITLE
"Permissions needed" showing on the Extensions button when not on a Google site

### ISSUE THREAD

**Issue by SigmaTheDJ** [bijij/ViewImage#273]
Since the most recent update to the extension, when you're not on a Google site, a green dot appears underneath the Extensions button in Firefox's toolbar: -

![1](https://github.com/bijij/ViewImage/assets/65978073/d80a6170-c1ba-48d3-b5bd-fb8872c8e831)

This is caused by the View Image extension: -

![2](https://github.com/bijij/ViewImage/assets/65978073/40e10780-be71-4e5c-8047-9a1a049db56e)

![3](https://github.com/bijij/ViewImage/assets/65978073/70471a52-c630-4513-95d3-86ddf0c30de3)

I cannot see any way to stop this from happening so I assume it's a bug, albeit a minor one that doesn't affect the core functionality.

The expected behaviour would be for View Image to not request permissions for any sites. Permissions are already granted for lots of different Google sites in the extension's own permissions list and the extension is only used with Google's image search sites.

I'm using version 4.0.0 of the extension with Firefox 115.0.2 on Windows 10.

**Comment by onestepbeyond** [comment]
Same here. 
Permission granted for all Google domains (or one unchecked at random for testing), the green dot invariably reappears.

**Comment by JLChamberlain** [comment]
Can also confirm this is happening for me. All permissions granted and as the others have stated the dot will appear on any non-google domains.

**Comment by bijij** [comment]
Hi there,
This seems to be a new initiative from mozilla for extensions with the `activeTab` permission who don't require access on all domains.

I've resolved it by disabling the ability to open the "search-by-image" context-menu item in the current tab.
A new release (v4.1.0) is coming shortly which should resolve this.
