### ISSUE TITLE
Userscript Update

### ISSUE THREAD

**Issue by Spuner** [bijij/ViewImage#274]
Is userscript no longer being updated?

**Comment by ner00** [comment]
I'm keep a fork for personal usage, it's working more often than not; here's the link: https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3

**Comment by ner00** [comment]
I keep updating a fork for personal use, it's working more often than not; here's the link: https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3

**Comment by Spuner** [comment]
Why is there one big button there - with text and icon? Can't you just leave the button with text, without the icon?

**Comment by ner00** [comment]
The button with the icon is to search similar images in a new tab; and like I said, this is mainly for personal use. Feel free to fork and tweak to your liking.

**Comment by Spuner** [comment]
Anyway, thanks for the script )

**Comment by bijij** [comment]
Thanks, everyone I've updated my copy as well.
