### ISSUE TITLE
"Permission needed to read and change data"

### ISSUE THREAD

**Issue by HulkSmashBurgers** [bijij/ViewImage#275]
Firefox 115.0.3

What does this mean? It's a minor issue, but I find the blue dot on the toolbar annoying.

![1](https://github.com/bijij/ViewImage/assets/2564116/4d4a2d71-21c2-4d6a-a483-01e30d43de24)
![2](https://github.com/bijij/ViewImage/assets/2564116/8f4bd6f4-91f7-4f18-a9b4-6ddbb9f56950)

**Comment by hhelibeb** [comment]
facing same issue, how to eliminate the dot🥺

**Comment by bijij** [comment]
duplicate of #273 this should go away with the next update.
