### ISSUE TITLE
Extension no longer works as of August 28th - Google changed layout

### ISSUE THREAD

**Issue by SigmaTheDJ** [bijij/ViewImage#276]
Google has changed the layout of their image search results and the "View image" and "Search by image" buttons no longer appear.

Here is an example when searching for "golden retriever" and clicking on one of the results: -

https://i.imgur.com/QM9ccme.jpg

I'm using Firefox 116.0.3 on Windows 10 and version 4.1.0 of the extension.

**Comment by ner00** [comment]
Google is using a new class name for the Visit button for some people; temporary workaround: https://github.com/bijij/ViewImage/issues/268#issuecomment-1476294452

**Comment by ner00** [comment]
Try to inspect the objects and report back https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3?permalink_comment_id=4624468#gistcomment-4624468

**Comment by Eter789** [comment]
> Try to inspect the objects and report back https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3?permalink_comment_id=4624468#gistcomment-4624468

Thank you, it worked perfectly for me

Note to all: Disable the extension for use the Tampermonkey script

**Comment by bijij** [comment]
Hey all, I'll release a new version with updated classes later today.

**Comment by Eter789** [comment]
> Hey all, I'll release a new version with updated classes later today.

Thank you

**Comment by bijij** [comment]
Hi all, just an update. The most recent release was rejected on the Chrome WebStore, due to a bug the tester encountered.

I'm going to attempt to reproduce, fix and reapply in the coming days.

**Comment by Eter789** [comment]
> Hi all, just an update. The most recent release was rejected on the Chrome WebStore, due to a bug the tester encountered.
> 
> I'm going to attempt to reproduce, fix and reapply in the coming days.

Got it
Thank you

**Comment by zelmor** [comment]
Is the manifest of the new release alright? I keep getting 
```
Manifest file is missing or unreadable
Could not load manifest.
```

**Comment by stevenirby** [comment]
> Is the manifest of the new release alright? I keep getting
> Manifest file is missing or unreadable
> Could not load manifest.

Same here.

**Comment by bijij** [comment]
> Is the manifest of the new release alright? I keep getting
> 
> ```
> Manifest file is missing or unreadable
> Could not load manifest.
> ```

Hi, is this one of the copies from an extension store, or using the release on GitHub?
If the latter the manifest.json file needs to be edited for each browser now (due to divergence in manifest v3 impls)

**Comment by Spuner** [comment]
@bijij, why don't you update the Chrome extension?

**Comment by zelmor** [comment]
@bijij my bad for not paying attention, renaming manifest.base.json to manifest.json fixed my issue. Thank you.

**Comment by Asqii** [comment]
Userscript version is not working either (not sure if its been updated though)

**Comment by ner00** [comment]
@Asqii Which userscript doesn't work? This one: https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3 or both?

**Comment by ner00** [comment]
So not both then, ok.

**Comment by jaredmcateer** [comment]
If you also install the "Google Images Restored" add-on this extension will work again. (I only tested on Firefox)

**Comment by afterdark1880** [comment]
> If you also install the "Google Images Restored" add-on this extension will work again. (I only tested on Firefox)

@jaredmcateer Thank you for your suggestion. Not what I intended, but still it works fine!

**Comment by jaredmcateer** [comment]
Totally, this is just a workaround, hopefully temporary

**Comment by nicolaasjan** [comment]
Meanwhile, the [userscript](https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3) from @ner00 still works (needs e.g. Violentmonkey extension).

**Comment by bijij** [comment]
Hi all, v5 of the extension has been released which should resolve these issues.

I'm waiting approval from Mozilla for Firefox, but the new version is available now for Chrome.

Thanks for your patience.
