### ISSUE TITLE
View Image v5.0.0 for Chrome still shows error asking for permission for goocatgle.rs and google.al

### ISSUE THREAD

**Issue by HighTechGeek** [bijij/ViewImage#278]
View Image v5.0.0 throws an error in Chrome on the drop down menu in the upper right corner of Chrome.

When expanded, it's wanting additional permissions.

![View Image error](https://github.com/bijij/ViewImage/assets/11942563/cfd3cf34-a81b-49b3-96c6-dcc46e35169e)

**Comment by bijij** [comment]
Hi there, this is not a bug.
I've updated the list of domains which the extension runs on to match those outlined in [google's supported domains list](https://www.google.com/supported_domains).

(Worth noting googlecat.rs was a typo and v5.0.1 resolves this)

If you want to use the extension you'll need to grant the additional permissions.

**Comment by fragmental** [comment]
I was unable to accept the new permissions.  When I clicked the button nothing happened.  In order to get the error to go away, and to make the extension work again, I uninstalled and reinstalled it.  This issue persisted across two different devices.

**Comment by bijij** [comment]
That sounds like an issue with your browser more so than the extension.

The permissions control UI is part of the browser itself.
