### ISSUE TITLE
Google Broke it again

### ISSUE THREAD

**Issue by L0garithmic** [bijij/ViewImage#279]
Google updated their page and nobody's scripts work any more. They moved things around.

IDK Why Google needs to always break things..

**Comment by bijij** [comment]
It seems Google has removed all the indicators I was using to tell this was a Google images page out of the URL.

I'm either going to need to find a new way to tell this is an images page.

Or just have the script always run on any google results page (not desirable).

**Comment by L0garithmic** [comment]
&udm=2

https://www.google.com/search?q=test&udm=2
https://www.google.com/search?q=test

**Comment by ner00** [comment]
It hasn't changed for me yet, it's still `&tbm=isch`, but how about `&udm=2`?

**Comment by L0garithmic** [comment]
both tbm=isch and udm=2 change the search to photos for me

**Comment by bijij** [comment]
I've added `udm=2` to the manifest in 3080a17 and bumped the version to 5.1.0, hopefully it doesn't take too long for webstores to approve.
