### ISSUE TITLE
Add Safari support

### ISSUE THREAD

**Issue by pushbox** [bijij/ViewImage#38]
Though I can download Chrome or Firefox to use this extension, I really hope you can support Safari as well. Maybe add a userscript version? So chrome/firefox/safari users can use it so long as they have Greasemonkey/Tampermonkey installed.
Thank you!

**Comment by bijij** [comment]
Userscript version of release 1.6.2

https://gist.github.com/bijij/58cc8cfc859331e4cf80210528a7b255
