### ISSUE TITLE
Image result dedicated page (middle click) does not have a button

### ISSUE THREAD

**Issue by asdgfd** [bijij/ViewImage#4]
When middle clicking on an image in the results, a new tab is created that is either a redirect to the page (Pinterest results usually result in a redirect, for example), or a dedicated page (the normal result of a middle click) which is similar to selecting/highlighting an image in the search results. This dedicated page does not seem to trigger the add-on as no view-image button appears.

**Comment by bijij** [comment]
Seems to have been fixed in 0ecfe2db8b57f9526872c9f7c8b88743f5fb52dc
