### ISSUE TITLE
Not working with Firefox ESR version

### ISSUE THREAD

**Issue by igorruckert** [bijij/ViewImage#45]
Extension not working with Firefox 52.6.0 ESR. Installed and nothing happened.

**Comment by deuxsonic** [comment]
I have the exact same problem.

**Comment by bijij** [comment]
I'm not 100% familiar with ESR, I'll be installing it later tonight and seeing what needs to be done to make the extension functional.

**Comment by geodock** [comment]
Not working with Firefox 52.0.2 w/ Windows XP either.

**Comment by deuxsonic** [comment]
I think it has to do with these versions of Firefox (anything prior to the split) using XUL/XPCOM add-ons.

**Comment by bijij** [comment]
I'll likely just make a userscript version rather than make a XUL extension.

**Comment by trlkly** [comment]
Arantius, creator of GreaseMonkey (and father of userscripts) still has his old Userscript to Firefox extension converter up on his site: https://arantius.com/misc/greasemonkey/script-compiler

**Comment by bijij** [comment]
https://github.com/bijij/ViewImage/releases/tag/1.0

XUL Extension

**Comment by EternityEngine** [comment]
For what it's worth, versions 1.4 and lower do work with Firefox 52.6.0 ESR.

**Comment by betterwebleon** [comment]
After testing the addon, this is the result I'm getting:
- Firefox 52.6.0 ESR 32-bit: "View Image" button is visible up to version 1.6.1, but not since 1.6.2.
- Firefox 52.6.0 ESR 64-bit: "View Image" button is visible up to version 1.4, but not since 1.5.2.

**Comment by bijij** [comment]
Does the XUL version function? if so I'll likely just use reccomend that be used for now.

**Comment by betterwebleon** [comment]
Yes, the XUL version functions on both FF ESR (32-bit and 64-bit) editions.

When it comes to 32-bit edition, it might be more convenient to install v1.6.1 (instead of unsigned XUL) and then disable automatic updates for this addon. Reason is that XUL version doesn't include toggle for "Open images in a new tab" among addon settings, and also lacks some translations.

**Comment by EternityEngine** [comment]
Interesting, because I'm running Firefox 52.6.0 ESR 32-bit and it only works up til 1.4 for me. XUL version works fine though.

**Comment by geodock** [comment]
Where can I download earlier versions?

**Comment by betterwebleon** [comment]
> Where can I download earlier versions?

Addon versions for Firefox are [here](https://addons.mozilla.org/firefox/addon/view-image/versions/).
All releases are also [here](https://github.com/bijij/ViewImage/releases) – for installing XUL extension look for ""viewimage.xpi" files.

**Comment by needforsuv** [comment]
I am on FF 51 64 bit can confirm only
1.4 and below works

**Comment by geodock** [comment]
Just installed V 1.4 and no it's working on FF 52 / Windows XP 32 bit.
