### ISSUE TITLE
Suggestion: add "search other sizes" button back too

### ISSUE THREAD

**Issue by fireattack** [bijij/ViewImage#47]
In the old Google image search interface, there was a size link right before "search by image":

![image](https://user-images.githubusercontent.com/4130991/36362256-71c875c2-14f8-11e8-9a00-3b9d428f7230.png)

And if you click it, it will do a reverse image search, but with "Tools > More sizes" activated.
This is very convenient when you're looking for other sizes of this exactly same picture. 

Of course, currently you can just click "search by image", then click "all sizes" (below)
![image](https://user-images.githubusercontent.com/4130991/36362279-b632ca8c-14f8-11e8-84f0-178aab9f35a5.png)

But since the whole point of this extension is to bring back convenience, I think this should be a reasonable request. 

Thanks!

**Comment by bijij** [comment]
Working on implementing this now.
Should be available online in about 6-8 hours.

**Comment by filips123** [comment]
In the old Google image search interface, there was a " - " (space, hyphen and space) character between the page name, the size, and the search by image link. Please add it back.
![google-view-image](https://user-images.githubusercontent.com/16626308/36371361-2a3de448-1562-11e8-9a70-07b46527c54b.png)

**Comment by bijij** [comment]
Having some issues with creating a link directly to the all sizes page.
If anyone has any idea how I'd do so that'd be useful.

The image size text however is implemented and ready to go.

**Comment by adrianiainlam** [comment]
Indeed there does not seem to be a simple way to link to the all sizes page.

One way (certainly not a good way) would be to send an XMLHttpRequest to the "Search by Image" page and parse the HTML for the "All sizes" link, noting the edge case that sometimes instead of the "All sizes" link it may say "No other sizes of this image found."

**Comment by bijij** [comment]
It seems processing that page is quite time consuming. So definitely want
to avoid an approach like that.
