### ISSUE TITLE
The "Visit"-button icon shows up on the "View Image"-button + language issue

### ISSUE THREAD

**Issue by MrDemocracy** [bijij/ViewImage#50]
<img width="398" src="https://user-images.githubusercontent.com/23060864/36384678-64f50c64-1590-11e8-8ac5-754ccb85f478.png">

Also, is it the system language that decides what language should be used on the ViewImage extension? I'd like to have my system languge set to english, while search results show up in my native language.
The way it is now, I see the buttons in both english and norwegian. 
Would it be possible to set the ViewImage-language to the same as my search results language?
If not could you make it possible to manually change the language on the settings page?

**Comment by bijij** [comment]
Locale in chrome extensions is defined by system lang yes.
I don't think i can change the locale used by an extension.

So the only solution I can think of is allowing custom text in these buttons. Which at the moment I'm not sure I want to do.

**Comment by MrDemocracy** [comment]
Okay, but what about the "Visit"-icon showing up on the the "View image"-button?

**Comment by bijij** [comment]
Oh whoops forgot to mention that. I'll change the alt text in the next
release.

**Comment by bijij** [comment]
Actually, the Globe icon was intentionally added as it was requested by a number of users. I think i'll keep it for now
