### ISSUE TITLE
View Image links back to original Google search

### ISSUE THREAD

**Issue by SpacebarStar** [bijij/ViewImage#52]
This is a really specific bug, and I have no idea what the cause is or if the issue's already been reported. When searching for "[nebula](https://www.google.nl/search?q=nebula&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiv8qOlkrPZAhURUlAKHWUgACIQ_AUICigB&biw=1745&bih=863#imgrc=9DEzmbXpsbbC9M:)" in google images and click View Image on the first 3864 × 3864 image from wikipedia, it links me back to my orginal google search.

**Comment by bijij** [comment]
Fixed in next release
