### ISSUE TITLE
Bug when opening search results in new tab

### ISSUE THREAD

**Issue by THEtomaso** [bijij/ViewImage#54]
**Description**:
When opening image search results in new tabs, the extension doesn't work.

**How to reproduce** (tested with XUL version 1.0 under Pale Moon, x64):
1) Search for some image.
2) Right-click on one of the search results and choose "Open link in new tab".
Result:
The extension doesn't work, and there's no "View image" and "Search by image" option.

**Comment by bijij** [comment]
This was related to an issue introduced in the standard 1.6.1 release. I'll update the XUL package with the fix in 1.6.2 later today at some point.

**Comment by THEtomaso** [comment]
You should consider hosting it at Pale Moon's extensions page:
https://addons.palemoon.org/extensions/

Instructions here:
http://developer.palemoon.org/Add-ons:Site/Submit

If you want to target it specifically for Pale Moon (not actually required), you'll find some info here:
https://forum.palemoon.org/viewtopic.php?f=19&t=16785/

..and in case you're wondering; no signing is required:
https://forum.palemoon.org/viewtopic.php?f=46&t=10570#p73714
:)
