### ISSUE TITLE
Does not work for all "Search Google for image" URLs

### ISSUE THREAD

**Issue by Hikari-chin** [bijij/ViewImage#55]
After using "Search Google for image" on an image from Chrome's right click context menu, this extension does not always display the "View image" button. For example:

- **Broken URL (nsfw-ish):**  https://www.google.com/search?q=nyantype+strike+the+blood&tbm=isch&tbs=simg:CAQSlwEJ5_1FikbyBttwaiwELEKjU2AQaBAgVCAcMCxCwjKcIGmIKYAgDEiinHKQcqByhHK4cohyjHOQDqhyvHNkjqCzYI6cs_1zmlLP452iO8J8U4GjBqT2PsSAH_1HG5Pm51g20FoZiLFntiHCNed6eNja-73ap_1rKE2scax1QrBQVeKZMdggBAwLEI6u_1ggaCgoICAESBM85uYYM,isz:l&sa=X&ved=0ahUKEwiju5XSj7XZAhWK7IMKHZwYCQQQ2A4IKSgD&biw=1536&bih=743&dpr=2.5#imgrc=oTfe25_EV-62xM:

- **Working URL:** https://www.google.com/search?q=strike+the+blood+personajes+nombres&tbm=isch&tbs=simg:CAQSlwEJXIixXqCD3uAaiwELEKjU2AQaBAgVCAAMCxCwjKcIGmIKYAgDEiiBG4cb4xv8DoUbtB-sHIwRpxyGG60soiyhLLsgvyPCI88j1yP6I58sGjCoaDsP_1i-E5mQLmh93nIcWtameRYaAikFdHm8It339a9x8BHOMneYAD03qH0dJWCYgBAwLEI6u_1ggaCgoICAESBLXkhNQM&sa=X&ved=0ahUKEwjkyuuqkbXZAhVo7oMKHeGuBYsQ2A4IJygB&biw=1536&bih=743&dpr=2.5#imgrc=-19MUHjkz9gBMM:

**Comment by bijij** [comment]
Fixed: I'll release a new version with this fix later today!
