### ISSUE TITLE
Does it need the permission of all the sites I've visited?

### ISSUE THREAD

**Issue by jrcharney** [bijij/ViewImage#56]
Almost clicked on the Install button for the Firefox version when it asked me if I could have access to my credentials for over 120 websites.  Can you elaborate on what this is used for before I consent?

**Comment by bijij** [comment]
In chrome/Firefox extensions you need to specify all top level domains which might be used.

Because google has different top level domains for each country (`google.com` for the US, `google.co.nz` for New Zealand etc.) the extension needs permission to run on every single one of these.

**Comment by jrcharney** [comment]
OK, just wanted to make sure.
