### ISSUE TITLE
Doesn't work with Pale Moon

### ISSUE THREAD

**Issue by psychonaut25** [bijij/ViewImage#57]
I'm using Pale Moon browser which is a fork of Firefox and it doesn't support WebExtensions.  Would you consider creating a ViewImage Greasemonkey script?

**Comment by bijij** [comment]
Hi I have created an unside [XUL](../tree/xul) version of this extension as well as a [userscript](https://gist.github.com/bijij/58cc8cfc859331e4cf80210528a7b255)

**Comment by bijij** [comment]
Closing as likley a duplicate of #45

**Comment by psychonaut25** [comment]
Thank you!
