### ISSUE TITLE
Bug - Extension doesn't always work

### ISSUE THREAD

**Issue by THEtomaso** [bijij/ViewImage#58]
**Description**:
For some images, the extenion still doesn't seem to work.

**Example**:
https://images.google.com/imgres?imgurl=https%3A%2F%2Fagushoe.files.wordpress.com%2F2014%2F06%2Fdscn5081.jpg&imgrefurl=https%3A%2F%2Fagushoe.wordpress.com%2F2014%2F06%2F02%2Fexplore-underwater-gili-kondo-east-lombok%2F&docid=1X8usO1VoiW1vM&tbnid=jgsPuFoWL0X14M%3A&vet=1&w=4608&h=3456&source=sh%2Fx%2Fim/

**Workaround**:
Click on one of the 'Related images', then back on the first one.
Then the extension suddenly works!

(Tested with XUL version 1.1 under Pale Moon x64)

**Comment by bijij** [comment]
This seems to be a weird case.

I can get the view image button to appear but I don't think it'll be able to display the high resolution image, only the thumbnail generated by google unfortunately.

**Comment by THEtomaso** [comment]
This one is even more weird:
https://www.google.com/imgres?imgurl=https%3A%2F%2Fmedia.wmagazine.com%2Fphotos%2F5852a2cdd3b7a5db18f377c7%2Fmaster%2Fpass%2FFINAL_NATALIE_PORTMAN.jpg&imgrefurl=https%3A%2F%2Fwww.wmagazine.com%2Fstory%2Fnatalie-portman-instagram-account&docid=rLu2CHTu2k21EM&tbnid=D4ziqt7Rm6KpVM%3A&vet=10ahUKEwi9kfnMn7nZAhXLDuwKHUhFCmIQMwg4KAcwBw..i&w=4912&h=7360&bih=858&biw=1280&q=natalie%20portman&ved=0ahUKEwi9kfnMn7nZAhXLDuwKHUhFCmIQMwg4KAcwBw&iact=mrc&uact=8

The workaround still seems to work (click on one of the 'Related images', then back on the first one to trigger the extension).
..but in this case, when clicking on the "View image" button", a different image appears!

**Comment by bijij** [comment]
For me using chrome extension v1.7  clicking the image shows me the thumbnail. 
v1.6.2 does show a different image. 
Not sure I can do any better than that unfortunately

I'll release an XUL v1.2 later today which shows the thumbnail

**Comment by bijij** [comment]
Fixed in release 1.2, or at least to an extent.
