### ISSUE TITLE
[Chrome Extension] Doesn't work in other "Related Images" thumbs.

### ISSUE THREAD

**Issue by Scott274** [bijij/ViewImage#64]
The Chrome version of ViewImage only works for the first image thumbnail when pulled down....but if you click on the other 7 "related image" thumbs besides the main one, no "view image" button or "search by image" button shows up for them.
Re-installed and restarted the browser, but still the same problem in Chrome.
This problem doesn't occur in Firefox (last I checked, about yesterday).

**Comment by bijij** [comment]
I'll publish a version with this fix momentarily
