### ISSUE TITLE
XUL version 1.2 - wrong version / nothing fixed

### ISSUE THREAD

**Issue by THEtomaso** [bijij/ViewImage#65]
I just gave the XUL version 1.2 a try..
It still says v1.1, and issue #58 is not fixed (no difference whatsoever).

**Comment by bijij** [comment]
Hi, I think I attached the old 1.1 release by mistake I've gone ahead and recompiled.
if the issues still persist I'll try and work on fixing them tomorrow.

**Comment by THEtomaso** [comment]
It states that it is v1.2 now, but unfortunately, issue #58 remains.

**Comment by bijij** [comment]
Okay, I'll see if I can do anything about that tomorrow

**Comment by THEtomaso** [comment]
Thanks.
We appreciate your efforts! :)
