### ISSUE TITLE
updateURL for userscript version

### ISSUE THREAD

**Issue by adrianiainlam** [bijij/ViewImage#66]
Thanks for the hard work.

Would you be intending to maintain the userscript version? If so, it would be nice to add a line

    // @updateURL https://gist.githubusercontent.com/bijij/58cc8cfc859331e4cf80210528a7b255/raw/viewimage.js

to the metadata block (and bump the version each time), so that GreaseMonkey etc can automatically look for updates.

**Comment by bijij** [comment]
I will be keeping the userscript updated yes.

I'll add that in now thanks.
