### ISSUE TITLE
View Image button not showing

### ISSUE THREAD

**Issue by bgilly** [bijij/ViewImage#68]
Chrome 64.0.3282.167 on Windows 10 (build 17074)
ViewImage extension v1.7.2

![screenshot_74](https://user-images.githubusercontent.com/1013672/36555529-22d70dea-17b7-11e8-80e8-91035d1907fc.png)

**Comment by edadams** [comment]
I'm having this problem too. macOS 10.13.2, Chrome 64.0.3282.167, extension version 1.7.2.

This error is being thrown in the dev tools console:

````
content-script.js:145 Uncaught TypeError: Cannot read property 'sync' of undefined
    at content-script.js:145
````

145 of `content-script.js` is:

````js
chrome.storage.sync.get(['options', 'defaultOptions'], function (storage) {
````

**Comment by VladimirSlavic** [comment]
down on linux mint 18.3 also

**Comment by TheSneakySniper** [comment]
down on os x 10.13.3 (17D102)

**Comment by LayoutXML** [comment]
Same. Chrome: Version 63.0.3239.132
Windows 10 Pro 1607 (14393)

**Comment by halvusvr** [comment]
same, broken

**Comment by hasan-r0ny** [comment]
It's broken. Fix it ASAP.

**Comment by bijij** [comment]
I'm going to assume it's a ratelimiting issue. With the fact I was writing the options to storage every time the extension reloaded.

**Comment by bijij** [comment]
i'll publish a version which doesn't do that

**Comment by bijij** [comment]
v 1.7.2.2 Published on FireFox store. seems to be functioning fine.
Waiting on chrome web store to publish.

**Comment by bijij** [comment]
Not 100% sure though. given "chrome.storage" being undefined really doesn't sound like something I did wrong.

**Comment by bgilly** [comment]
Thank you! I appreciate your work on this.

**Comment by iamvinny** [comment]
It's not showing sometimes when I reverse image search

Chrome version: 71.0.3578.98 (Official Build) (64-bit) on MacOS 10.13.6
