### ISSUE TITLE
XUL Version seriously lacking in features.

### ISSUE THREAD

**Issue by bijij** [bijij/ViewImage#70]
I really would like to impliment the settings toggles seen in the chrome extension in the XUL version.
However I really have basically no experience with how XUL extensions work or how one would go about doing that.

**Comment by Ascrod** [comment]
Hello! Just thought I'd let you know that I'm working on updating this. I'll submit a PR when I think it's in a good state.
https://github.com/Ascrod/ViewImage/tree/xul

**Comment by Ascrod** [comment]
Is there still any interest in maintaining the XUL branch? This PR has been open for quite a while and some users of the XUL extension are asking about a release. Any thoughts or feedback?

**Comment by bijij** [comment]
going to be honest I completely missed you'd pushed a PR my bad
