### ISSUE TITLE
Tampermonkey

### ISSUE THREAD

**Issue by PentagramTr** [bijij/ViewImage#74]
Hi.

I do not want to install the extension. Can I use this extension with Tampermonkey?

Edit: I added `viewimage.js` to Tampermonkey, but it did not work.

**Comment by bijij** [comment]
Hi, might have been caused by the file not ending in `.user.js` does adding

https://gist.githubusercontent.com/bijij/58cc8cfc859331e4cf80210528a7b255/raw/9017e1b7bf2996da85aab0f6065e9985dabd453a/viewimage.user.js

To tampermonkey work?

**Comment by PentagramTr** [comment]
Hi.
I added the code to Tampermonkey, but it did not work.

![t1](https://user-images.githubusercontent.com/34379403/36685765-6078c50e-1b35-11e8-8056-2ef140461906.png)
![t2](https://user-images.githubusercontent.com/34379403/36685766-60a16d88-1b35-11e8-86b0-1b393372421d.png)
![tampermonkey](https://user-images.githubusercontent.com/34379403/36685767-60c4af5a-1b35-11e8-8b39-22cfa32f5cd6.png)
