### ISSUE TITLE
Fix Userscript extension. 

### ISSUE THREAD

**Issue by trlkly** [bijij/ViewImage#78]
Please rename the userscript to end in `.user.js`, so that it will actually be detected by the various UserScript managers (e.g. Tampermonkey, GreaseMonkey) as a userscript.

**Comment by bijij** [comment]
I've gone ahead and done this. I guess technically this is a breaking change. 
Raw now located at

https://gist.githubusercontent.com/bijij/58cc8cfc859331e4cf80210528a7b255/raw/9017e1b7bf2996da85aab0f6065e9985dabd453a/viewimage.user.js
