### ISSUE TITLE
Brazilian Portuguese Firefox showing texts in english.

### ISSUE THREAD

**Issue by UNREALWINS** [bijij/ViewImage#8]
Please, put a option to we write the text of the two options or make a option to translate.

Thanks

**Comment by danielhickman** [comment]
Locales could be added for the front-facing texts where users can supply translations. Google is vigilant about adding [`lang="en"`](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) to the HTML tag but should still fall back on English.

**Comment by bijij** [comment]
I would prefer to have direct translations via locales.
ideally /_locales/en/messages.json would be translated to Portugese so that there is no need for end user intervention.

**Comment by UNREALWINS** [comment]
Bijij, Great! I made it! Thanks!
