### ISSUE TITLE
Slider Options don't save in chrome 

### ISSUE THREAD

**Issue by needforsuv** [bijij/ViewImage#83]
The slider options don't seem to save on the current chrome store version
it saves the custom text I entered but the options sliders always reset to default

**Comment by BestBackwards** [comment]
I can confirm the same experience from here
Extension version: 1.7.2.3
Chrome version: 64.0.3282.186 (Official Build) (64-bit)

**Comment by bijij** [comment]
I think I've found the issue, this should be fixed in the next release

**Comment by bijij** [comment]
Issue should be fixed in 1.8 release, which has been rolled out now. Waiting on processing from Google and Mozilla.

**Comment by BestBackwards** [comment]
Apologies to do this to you, I'm not able to confirm this is resolved. I appreciate the effort you put in and I love the extension
Extension version: 1.8.1
Chrome version: 64.0.3282.186 (Official Build) (64-bit)
