### ISSUE TITLE
Mistranslation

### ISSUE THREAD

**Issue by PentagramTr** [bijij/ViewImage#89]
Hi.

The word " **seçenekleri** " are incorrect.The correct spelling will be " **Seçenekler** "There's an extra 1 character at the end of word.The 1 character at the end break the meaning of word.

Would you please update extension?

![https-github com-bijij-viewimage-issues-new](https://user-images.githubusercontent.com/34379403/36686388-51187224-1b37-11e8-9eb9-5c295ce900aa.png)

**Comment by bijij** [comment]
fixed in next release
