### ISSUE TITLE
1.8 won't install, says corrupt

### ISSUE THREAD

**Issue by csc-mio** [bijij/ViewImage#90]
Installed the last version ok - yesterday, went to install on different Firefox and won't install - says may be corrupt https://addons.mozilla.org/en-US/firefox/addon/view-image/

**Comment by Acid-Crash** [comment]
Hi, same here. Not sure if this is related but the highlighted ru locale path looks unusual to me
![json](https://user-images.githubusercontent.com/32600318/36692629-484c1b32-1b41-11e8-9f35-2f73d57e6008.png)

**Comment by needforsuv** [comment]
Same problem with chrome
Package is invalid. Details: 'Messages file is missing for locale. C:\Users\user\AppData\Local\Temp\scoped_dir_7972_12100\CRX_INSTALL\_locales\ru\messages.json'.

**Comment by LexCybermac** [comment]
Same issue when trying to intall with Vivaldi:
![capture](https://user-images.githubusercontent.com/23614403/36717417-eb65a9e2-1b95-11e8-8ea1-e365ec650773.PNG)

**Comment by danid12** [comment]
not working for me too. after saw that the options i change in settings not saved i tried to reinstall and this is there the error i get: 
https://i.imgur.com/MpV2gvc.png

**Comment by bijij** [comment]
I'll be releasing a fixed version momentarily, sorry about that.

**Comment by Acid-Crash** [comment]
Hi, 1.8.1 fixes it of Firefox

**Comment by kulaLin** [comment]
We want to know, why does this happen?

**Comment by bijij** [comment]
Is this fixed in 1.8.1?

@kulaLin this was caused by the Ru locales not being named correctly

**Comment by Lewandelein** [comment]
It works :+1:  thank you very very much you saved my day

**Comment by csc-mio** [comment]
Great - installing fine - thanks for quick fix!
