### ISSUE TITLE
options not saved

### ISSUE THREAD

**Issue by danid12** [bijij/ViewImage#94]
it is not working in the newest version of extension,
 in newest chrome stable version.
now when you toggle to try to change the default 
options to blue/ grey it's not saved.
it's only stay on default. 
only text added is saved but it doesn't effect anything because when you try
to make it blue it is not saved.

**Comment by needforsuv** [comment]
Same issue as #83 
I guess its not fixed YET

**Comment by bijij** [comment]
I can't replicate this. My options are always saved when I use the release version. Only thing It could be is ratelimit related.

Where if the options are saved too often it'll start failing to save.

I'll replace autosave with a save button in an upcoming release then.

**Comment by PointyDev** [comment]
Can repro - `v1.8.1 (win x86-64) - en_GB` - Chrome Web Store release
Appreciate your plugin, even if it only saves a few milliseconds in my use case hehe

**Comment by git-fr** [comment]
Same problem of option changes not saving, in Chrome Portable, an old version.  It came from https://portableapps.com/apps/internet/google_chrome_portable and apparently I haven't updated in a while.

From chrome://version, it's:
- **Google Chrome** | 58.0.3029.110 (Official Build) (32-bit)
- **Revision** | 691bdb490962d4e6ae7f25c6ab1fdd0faaf19cd0-refs/branch-heads/3029@{#830}
- **OS** | Windows
- **JavaScript** | V8 5.8.283.38
- **Flash** | 28.0.0.161 C:\localhome\Chrome Portable\GoogleChromePortable\Data\profile\PepperFlash\28.0.0.161\pepflashplayer.dll
- User Agent | Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
- **Command Line** | "C:\localhome\Chrome Portable\GoogleChromePortable\App\Chrome-bin\chrome.exe" --user-data-dir="C:\localhome\Chrome Portable\GoogleChromePortable\Data\profile" --disk-cache-dir="C:\Users\swiener\AppData\Local\Temp\GoogleChromePortable" --flag-switches-begin --flag-switches-end

**Comment by bijij** [comment]
Are there any errors in the JS console when using the toggles and such?
