### ISSUE TITLE
Several Websites Not Supported

### ISSUE THREAD

**Issue by kimkash** [bijij/ViewImage#99]
Noticed that while searching for pictures, clicking the "View Image" button when it is pictures from Reddit and Cnet- the thumbnail would load and not the full size picture.
Searched for 20MP and above, if the helps in any way...

**Comment by bijij** [comment]
can you provie an example link?

**Comment by needforsuv** [comment]
Some websites may redirect based on http or https
example: (shared link - thumbnail) https://goo.gl/images/oYaY5T
(raw search - redirected to https website)
https://www.google.com.au/search?q=reddit&tbm=isch&source=lnt&tbs=isz:lt,islt:20mp&sa=X&ved=0ahUKEwjas-CkvczZAhUMw7wKHeHHBgEQpwUIIA&biw=1691&bih=846&dpr=1#imgrc=BT0BhJF5yc5dDM:
if you view image from reddit it works
if the view image link is
i.imgur.com/YMmOsVR.jpg it MAY not work
if it is
https://i.imgur.com/YMmOsVR.jpg it probably works
I'd say this is a hotlinking problem... try checking with another search engine with view image

**Comment by keombre** [comment]
My guess is that it has to do more with direct search `www.google.com.au` and embedded(?) search `images.google.com.au`.

**Comment by bijij** [comment]
Really seems like too much of a niche to change how things work. possibly breaking other results pages to fix.

**Comment by keombre** [comment]
Now seems to have automagically fixed itself. (Tested with Chrome 63 and 64 in Win 10 x64) Maybe someone at Google helped us? 😏

You can probably update tags.
